# Generated by Django 5.1.3 on 2026-02-23 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFormLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, help_text='Auto-generated from organization name.', max_length=300, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('custom_branding_enabled', models.BooleanField(default=False, help_text="When enabled, a 'Custom Name' column is added to the live sheet and included in all admin exports.")),
                ('expires_at', models.DateTimeField(help_text='The form locks automatically at this datetime. The live sheet shows a real-time countdown to this moment.')),
                ('max_submissions', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited submissions.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to close the form immediately, regardless of expiry.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_submission_at', models.DateTimeField(blank=True, null=True)),
                ('last_serial_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_form_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Form Link',
                'verbose_name_plural': 'Live Form Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveFormEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.PositiveIntegerField(editable=False)),
                ('full_name', models.CharField(max_length=255)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='live_forms.liveformlink')),
            ],
            options={
                'verbose_name': 'Live Form Entry',
                'verbose_name_plural': 'Live Form Entries',
                'ordering': ['live_form', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='liveformlink',
            index=models.Index(fields=['created_by', 'expires_at'], name='liveform_user_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformlink',
            index=models.Index(fields=['organization_name'], name='liveform_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformlink',
            index=models.Index(fields=['created_at'], name='liveform_created_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformlink',
            index=models.Index(fields=['slug'], name='liveform_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformlink',
            index=models.Index(fields=['is_active'], name='liveform_active_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformentry',
            index=models.Index(fields=['live_form', 'serial_number'], name='liveform_entry_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformentry',
            index=models.Index(fields=['live_form', 'created_at'], name='liveform_entry_created_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformentry',
            index=models.Index(fields=['full_name'], name='liveform_entry_name_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformentry',
            index=models.Index(fields=['size'], name='liveform_entry_size_idx'),
        ),
        migrations.AddIndex(
            model_name='liveformentry',
            index=models.Index(fields=['updated_at'], name='liveform_entry_updated_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liveformentry',
            unique_together={('live_form', 'serial_number')},
        ),
    ]
