# Generated by Django 5.1.3 on 2026-02-23 06:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelBulkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('coordinator_name', models.CharField(max_length=255)),
                ('coordinator_email', models.EmailField(max_length=254)),
                ('coordinator_phone', models.CharField(max_length=20)),
                ('title', models.CharField(help_text="e.g., 'NYSC Batch C Stream 1 Camp'", max_length=255)),
                ('price_per_participant', models.DecimalField(decimal_places=2, help_text='Price per participant in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requires_custom_name', models.BooleanField(default=False, help_text='If True, Custom Name column will appear in Excel template')),
                ('template_file', models.URLField(blank=True, help_text='Cloudinary URL of generated Excel template', null=True)),
                ('uploaded_file', models.URLField(blank=True, help_text='Cloudinary URL of uploaded Excel with participant data', null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'File Uploaded - Not Validated'), ('valid', 'Validated - Ready for Payment'), ('invalid', 'Validation Failed'), ('processing', 'Processing Payment'), ('completed', 'Payment Complete')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, help_text='Detailed validation errors for uploaded Excel', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount to be paid (excluding couponed participants)', max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_bulk_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excel Bulk Order',
                'verbose_name_plural': 'Excel Bulk Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelCouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='excel_bulk_orders.excelbulkorder')),
            ],
            options={
                'verbose_name': 'Excel Coupon Code',
                'verbose_name_plural': 'Excel Coupon Codes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=10)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_coupon_applied', models.BooleanField(default=False, help_text='True if valid coupon was used (participant not charged)')),
                ('row_number', models.PositiveIntegerField(help_text='Original row number from Excel file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='excel_bulk_orders.excelbulkorder')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='excel_bulk_orders.excelcouponcode')),
            ],
            options={
                'verbose_name': 'Excel Participant',
                'verbose_name_plural': 'Excel Participants',
                'ordering': ['bulk_order', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='excelbulkorder',
            index=models.Index(fields=['reference'], name='excel_bulk_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='excelbulkorder',
            index=models.Index(fields=['coordinator_email'], name='excel_bulk_email_idx'),
        ),
        migrations.AddIndex(
            model_name='excelbulkorder',
            index=models.Index(fields=['validation_status'], name='excel_bulk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='excelbulkorder',
            index=models.Index(fields=['payment_status'], name='excel_bulk_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='excelbulkorder',
            index=models.Index(fields=['created_at'], name='excel_bulk_created_idx'),
        ),
        migrations.AddIndex(
            model_name='excelcouponcode',
            index=models.Index(fields=['bulk_order', 'is_used'], name='excel_coupon_bulk_used_idx'),
        ),
        migrations.AddIndex(
            model_name='excelcouponcode',
            index=models.Index(fields=['code'], name='excel_coupon_code_idx'),
        ),
        migrations.AddIndex(
            model_name='excelparticipant',
            index=models.Index(fields=['bulk_order', 'row_number'], name='excel_part_bulk_row_idx'),
        ),
        migrations.AddIndex(
            model_name='excelparticipant',
            index=models.Index(fields=['full_name'], name='excel_part_name_idx'),
        ),
        migrations.AddIndex(
            model_name='excelparticipant',
            index=models.Index(fields=['size'], name='excel_part_size_idx'),
        ),
        migrations.AddIndex(
            model_name='excelparticipant',
            index=models.Index(fields=['is_coupon_applied'], name='excel_part_coupon_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='excelparticipant',
            unique_together={('bulk_order', 'row_number')},
        ),
    ]
