# Generated by Django 5.1.3 on 2026-02-23 06:59

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import referrals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the promotional media', max_length=255)),
                ('media_type', models.CharField(choices=[('flyer', 'Flyer'), ('video', 'Video')], help_text='Type of media', max_length=10)),
                ('media_file', cloudinary.models.CloudinaryField(blank=True, help_text='Promotional media file (image or video)', max_length=255, null=True, verbose_name='media')),
                ('marketing_text', models.TextField(help_text='Pre-written marketing text for sharing')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this media is currently active for sharing')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin user who created this media', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotional_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotional Media',
                'verbose_name_plural': 'Promotional Media',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='referrals_p_is_acti_de0369_idx'), models.Index(fields=['media_type'], name='referrals_p_media_t_4d317e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferrerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(default=referrals.models.generate_referral_code, editable=False, help_text='Unique referral code', max_length=8, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the referrer', max_length=255)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=255)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this referrer profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User associated with this referrer profile', on_delete=django.db.models.deletion.CASCADE, related_name='referrer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referrer Profile',
                'verbose_name_plural': 'Referrer Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referral_code'], name='referrals_r_referra_166b16_idx'), models.Index(fields=['user'], name='referrals_r_user_id_7138d2_idx'), models.Index(fields=['is_active'], name='referrals_r_is_acti_af2a77_idx')],
            },
        ),
    ]
