# Generated by Django 5.1.3 on 2026-02-23 06:59

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBulkOrderLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('custom_branding_enabled', models.BooleanField(default=False)),
                ('payment_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_bulk_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Bulk Order Link',
                'verbose_name_plural': 'Image Bulk Order Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageCouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='image_bulk_orders.imagebulkorderlink')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageOrderEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.PositiveIntegerField(editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=10)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional image upload (will be organized by order slug and size)', max_length=255, null=True, verbose_name='image')),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='image_bulk_orders.imagebulkorderlink')),
                ('coupon_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_bulk_orders.imagecouponcode')),
            ],
            options={
                'verbose_name': 'Image Order Entry',
                'verbose_name_plural': 'Image Order Entries',
                'ordering': ['bulk_order', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['created_by', 'payment_deadline'], name='img_bulk_user_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['organization_name'], name='img_bulk_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['created_at'], name='img_bulk_created_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebulkorderlink',
            index=models.Index(fields=['slug'], name='img_bulk_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecouponcode',
            index=models.Index(fields=['bulk_order', 'is_used'], name='img_coupon_bulk_used_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecouponcode',
            index=models.Index(fields=['code'], name='img_coupon_code_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['bulk_order', 'serial_number'], name='img_order_bulk_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['email'], name='img_order_email_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['paid'], name='img_order_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['size'], name='img_order_size_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['created_at'], name='img_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['updated_at'], name='img_order_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='imageorderentry',
            index=models.Index(fields=['reference'], name='img_order_reference_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imageorderentry',
            unique_together={('bulk_order', 'serial_number')},
        ),
    ]
