# academic_directory/management/commands/state_data/anambra.py
"""Universities in Anambra State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'Nnamdi Azikiwe University, Awka',
        'abbreviation': 'UNIZIK',
        'state': 'ANAMBRA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Agriculture', 'abbreviation': 'AGR'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science and Horticulture', 'abbreviation': 'CSH'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Food Science and Technology', 'abbreviation': 'FST'},
                    {'name': 'Forestry and Wildlife', 'abbreviation': 'FWL'},
                    {'name': 'Soil Science and Soil Resources Management', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'African and Asian Studies', 'abbreviation': 'AAS'},
                    {'name': 'Chinese Studies', 'abbreviation': 'CHS'},
                    {'name': 'English Language and Literature', 'abbreviation': 'ELL'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Modern and European Languages', 'abbreviation': 'MEL'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Religious and Human Relations', 'abbreviation': 'RHR'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Biosciences',
                'abbreviation': 'BIO',
                'departments': [
                    {'name': 'Applied Biochemistry', 'abbreviation': 'ABC'},
                    {'name': 'Applied Microbiology and Brewing', 'abbreviation': 'AMB'},
                    {'name': 'Biological Science', 'abbreviation': 'BSC'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Parasitology and Entomology', 'abbreviation': 'PEN'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Adult Education', 'abbreviation': 'ADE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Early Childhood and Primary Education', 'abbreviation': 'ECP'},
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education and Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education and English Language', 'abbreviation': 'EDEL'},
                    {'name': 'Education and French', 'abbreviation': 'EDF'},
                    {'name': 'Education and Igbo', 'abbreviation': 'EDI'},
                    {'name': 'Education and Integrated Science', 'abbreviation': 'EDIS'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Education and Political Science', 'abbreviation': 'EDPS'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Educational Management and Policy', 'abbreviation': 'EMP'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Library and Information Management', 'abbreviation': 'LIM'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural and Bioresources Engineering', 'abbreviation': 'ABE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical Engineering', 'abbreviation': 'ELE'},
                    {'name': 'Electronics and Computer Engineering', 'abbreviation': 'ECE'},
                    {'name': 'Industrial Production Engineering', 'abbreviation': 'IPE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Metallurgical and Materials Engineering', 'abbreviation': 'MME'},
                    {'name': 'Polymer and Textile Engineering', 'abbreviation': 'PTE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Environmental Management', 'abbreviation': 'ENM'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                    {'name': 'Geography and Meteorology', 'abbreviation': 'GEM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                ],
            },
            {
                'name': 'Faculty of Health Sciences and Technology',
                'abbreviation': 'HST',
                'departments': [
                    {'name': 'Environmental Health Science', 'abbreviation': 'EHS'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Medical Rehabilitation', 'abbreviation': 'MRE'},
                    {'name': 'Radiography', 'abbreviation': 'RAD'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Civil Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Cooperative Economics and Management', 'abbreviation': 'CEM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Medical Laboratory Sciences',
                'abbreviation': 'MLS',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                ],
            },
            {
                'name': 'Faculty of Medicine',
                'abbreviation': 'MED',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                ],
            },
            {
                'name': 'Faculty of Pharmaceutical Sciences',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'Faculty of Physical Sciences',
                'abbreviation': 'PSC',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geological Sciences', 'abbreviation': 'GLS'},
                    {'name': 'Geophysics', 'abbreviation': 'GPH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics and Industrial Physics', 'abbreviation': 'PHY'},
                    {'name': 'Pure and Industrial Chemistry', 'abbreviation': 'PIC'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Sociology and Anthropology', 'abbreviation': 'SOA'},
                ],
            },
        ],
    },
    {
        'name': 'Chukwuemeka Odumegwu Ojukwu University, Igbariam',
        'abbreviation': 'COOU',
        'state': 'ANAMBRA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Agriculture', 'abbreviation': 'AGR'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Fishery and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Food Science and Technology', 'abbreviation': 'FST'},
                    {'name': 'Forestry and Wildlife Management', 'abbreviation': 'FWL'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Igbo and Linguistics', 'abbreviation': 'IGB'},
                    {'name': 'Linguistics and Igbo Language', 'abbreviation': 'LIN'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Religion', 'abbreviation': 'REL'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education and Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education and English Language', 'abbreviation': 'EDEL'},
                    {'name': 'Education and Igbo', 'abbreviation': 'EDI'},
                    {'name': 'Education and Integrated Science', 'abbreviation': 'EDIS'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Health Education', 'abbreviation': 'HED'},
                    {'name': 'Human Kinetics', 'abbreviation': 'HKI'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural and Bioresources Engineering', 'abbreviation': 'ABE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                    {'name': 'Geography and Meteorology', 'abbreviation': 'GEM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Medicine',
                'abbreviation': 'MED',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                ],
            },
            {
                'name': 'Faculty of Natural Sciences',
                'abbreviation': 'NAT',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Pharmaceutical Sciences',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'Faculty of Physical Sciences',
                'abbreviation': 'PSC',
                'departments': [
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
        ],
    },
    {
        'name': 'Madonna University, Okija',
        'abbreviation': 'MADONNA',
        'state': 'ANAMBRA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'College of Medicine',
                'abbreviation': 'MED',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Education and Art',
                'abbreviation': 'EDA',
                'departments': [
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'English', 'abbreviation': 'ENG'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Petroleum Engineering', 'abbreviation': 'PET'},
                    {'name': 'Food Science Technology', 'abbreviation': 'FST'},
                ],
            },
            {
                'name': 'Faculty of Health Sciences',
                'abbreviation': 'HSC',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Nursing', 'abbreviation': 'NSG'},
                    {'name': 'Optometry', 'abbreviation': 'OPT'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                    {'name': 'International Law', 'abbreviation': 'INL'},
                    {'name': 'Private Law', 'abbreviation': 'PRL'},
                    {'name': 'Public Law', 'abbreviation': 'PUL'},
                ],
            },
            {
                'name': 'Faculty of Management',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking', 'abbreviation': 'BNK'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Finance', 'abbreviation': 'FIN'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Pharmacy',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                    {'name': 'Applied Chemistry', 'abbreviation': 'APC'},
                    {'name': 'Biotechnology', 'abbreviation': 'BTC'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Pharmacology', 'abbreviation': 'PHC'},
                    {'name': 'Toxicology', 'abbreviation': 'TOX'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'International Relations and Diplomacy', 'abbreviation': 'IRD'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Political Sciences', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
        ],
    },
    {
        'name': 'Tansian University, Umunya',
        'abbreviation': 'TANU',
        'state': 'ANAMBRA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Electronics and Automation', 'abbreviation': 'ELA'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Telecommunications Technology', 'abbreviation': 'TCT'},
                ],
            },
            {
                'name': 'College of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking', 'abbreviation': 'BNK'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Criminology', 'abbreviation': 'CRM'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Finance', 'abbreviation': 'FIN'},
                    {'name': 'International Relations and Diplomacy', 'abbreviation': 'IRD'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Political Sciences', 'abbreviation': 'POL'},
                    {'name': 'Protective Services', 'abbreviation': 'PRS'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Art Education', 'abbreviation': 'ARE'},
                    {'name': 'Education', 'abbreviation': 'EDN'},
                    {'name': 'Humanities and Social Science Education', 'abbreviation': 'HSE'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Special Education', 'abbreviation': 'SPE'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Real Estate', 'abbreviation': 'RES'},
                    {'name': 'Regional Planning', 'abbreviation': 'RPL'},
                    {'name': 'Town Planning', 'abbreviation': 'TWP'},
                ],
            },
            {
                'name': 'Faculty of Health Sciences',
                'abbreviation': 'HSC',
                'departments': [
                    {'name': 'Laboratory Techniques', 'abbreviation': 'LBT'},
                    {'name': 'Nursing', 'abbreviation': 'NSG'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Civil Law', 'abbreviation': 'LAW'},
                ],
            },
        ],
    },
    {
        'name': 'Paul University, Awka',
        'abbreviation': 'PAUL',
        'state': 'ANAMBRA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'English Literature', 'abbreviation': 'ELT'},
                    {'name': 'History and International Relations', 'abbreviation': 'HIR'},
                    {'name': 'Religion', 'abbreviation': 'REL'},
                    {'name': 'Theater Arts', 'abbreviation': 'THA'},
                    {'name': 'Theology', 'abbreviation': 'THO'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Health Information Management', 'abbreviation': 'HIM'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Management and Entrepreneurial Studies', 'abbreviation': 'MES'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Management Information System', 'abbreviation': 'MIS'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Pure and Industrial Chemistry', 'abbreviation': 'PIC'},
                    {'name': 'Pure Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Allied Medical Sciences',
                'abbreviation': 'AMS',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Nursing', 'abbreviation': 'NSG'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Education', 'abbreviation': 'EDN'},
                ],
            },
        ],
    },
    {
        'name': 'Legacy University, Okija',
        'abbreviation': 'LUO',
        'state': 'ANAMBRA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Arts and Humanities',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Oko',
        'abbreviation': 'OKOPOLY',
        'state': 'ANAMBRA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Insurance', 'abbreviation': 'INS'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Agricultural Engineering Technology', 'abbreviation': 'AET'},
                    {'name': 'Civil Engineering Technology', 'abbreviation': 'CET'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                ],
            },
            {
                'name': 'School of Environmental Design',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'School of Industrial and Applied Sciences',
                'abbreviation': 'SIA',
                'departments': [
                    {'name': 'Arts and Design', 'abbreviation': 'ARD'},
                    {'name': 'Fashion Design and Clothing Technology', 'abbreviation': 'FDT'},
                    {'name': 'Food Technology', 'abbreviation': 'FST'},
                    {'name': 'Home and Rural Economics', 'abbreviation': 'HRE'},
                    {'name': 'Hospitality Management', 'abbreviation': 'HMT'},
                    {'name': 'Printing Technology', 'abbreviation': 'PRT'},
                ],
            },
            {
                'name': 'School of Information and Communication Technology',
                'abbreviation': 'ICT',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'School of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                ],
            },
        ],
    },
    {
        'name': 'Anambra State Polytechnic, Mgbakwu',
        'abbreviation': 'ANSPOLY',
        'state': 'ANAMBRA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Agriculture and Related Disciplines',
                'abbreviation': 'SAD',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGR'},
                    {'name': 'Animal Health and Production Technology', 'abbreviation': 'AHP'},
                    {'name': 'Home and Rural Economics', 'abbreviation': 'HRE'},
                    {'name': 'Fishery Technology', 'abbreviation': 'FIS'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Electrical and Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Computer Engineering Technology', 'abbreviation': 'CPE'},
                ],
            },
            {
                'name': 'School of Management Science',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Cooperative Economics and Management', 'abbreviation': 'CEM'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science Technology', 'abbreviation': 'CST'},
                    {'name': 'Nutrition and Dietetics', 'abbreviation': 'NUD'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                ],
            },
        ],
    },
]