# academic_directory/management/commands/state_data/bauchi.py
"""Universities in Bauchi State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'Abubakar Tafawa Balewa University, Bauchi',
        'abbreviation': 'ATBU',
        'state': 'BAUCHI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'College of Medical Sciences',
                'abbreviation': 'CMS',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Nursing', 'abbreviation': 'NSG'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Radiography', 'abbreviation': 'RAD'},
                    {'name': 'Physiotherapy', 'abbreviation': 'PTP'},
                ],
            },
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Animal Production', 'abbreviation': 'ANP'},
                    {'name': 'Crop Production', 'abbreviation': 'CRP'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Engineering and Engineering Technology',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural Engineering', 'abbreviation': 'AGE'},
                    {'name': 'Automobile Engineering', 'abbreviation': 'AUE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer and Communication Engineering', 'abbreviation': 'CCE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Mechanical and Production Engineering', 'abbreviation': 'MPE'},
                    {'name': 'Mechatronics and System Engineering', 'abbreviation': 'MSE'},
                    {'name': 'Petrochemical Engineering', 'abbreviation': 'PCE'},
                    {'name': 'Petroleum Engineering', 'abbreviation': 'PET'},
                ],
            },
            {
                'name': 'Faculty of Environmental Technology',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Environmental Management Technology', 'abbreviation': 'EMT'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Industrial Design', 'abbreviation': 'IND'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Management Technology',
                'abbreviation': 'FMT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance Technology', 'abbreviation': 'BNF'},
                    {'name': 'Business Management', 'abbreviation': 'BUM'},
                    {'name': 'Management and Information Technology', 'abbreviation': 'MIT'},
                    {'name': 'Technopreneurship', 'abbreviation': 'TNP'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biological Sciences', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Ecology', 'abbreviation': 'ECO'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Mathematical Sciences', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Technology Education',
                'abbreviation': 'TED',
                'departments': [
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education and Integrated Science', 'abbreviation': 'EDIS'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Education and Science', 'abbreviation': 'EDS'},
                    {'name': 'Education Foundation', 'abbreviation': 'EDF'},
                    {'name': 'Electrical and Electronics Education', 'abbreviation': 'EEE'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Vocational and Technology Education', 'abbreviation': 'VTE'},
                    {'name': 'Woodwork Technology Education', 'abbreviation': 'WTE'},
                ],
            },
        ],
    },
    {
        'name': 'Bauchi State University, Gadau',
        'abbreviation': 'BASUG',
        'state': 'BAUCHI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agriculture', 'abbreviation': 'AGR'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'Arabic Studies', 'abbreviation': 'ARA'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'Hausa', 'abbreviation': 'HAU'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISC'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Literature in English', 'abbreviation': 'LIE'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Human Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Human Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Pharmacology', 'abbreviation': 'PHC'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education and English Language', 'abbreviation': 'EDEL'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Pharmaceutical Sciences',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Doctor of Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biological Sciences', 'abbreviation': 'BIO'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Environmental Health', 'abbreviation': 'ENV'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Health Technology', 'abbreviation': 'PHT'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Bauchi',
        'abbreviation': 'FPTB',
        'state': 'BAUCHI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Agricultural and Bio-Environmental Engineering Technology', 'abbreviation': 'ABE'},
                    {'name': 'Chemical Engineering Technology', 'abbreviation': 'CET'},
                    {'name': 'Civil Engineering Technology', 'abbreviation': 'CVT'},
                    {'name': 'Computer Engineering Technology', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                    {'name': 'Mechatronics Engineering Technology', 'abbreviation': 'MCE'},
                ],
            },
            {
                'name': 'School of Environmental Technology',
                'abbreviation': 'SENT',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                ],
            },
            {
                'name': 'School of Agricultural Technology',
                'abbreviation': 'SAT',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGR'},
                    {'name': 'Animal Health and Production Technology', 'abbreviation': 'AHP'},
                    {'name': 'Forestry Technology', 'abbreviation': 'FOR'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Food Technology', 'abbreviation': 'FST'},
                    {'name': 'Hospitality Management', 'abbreviation': 'HMT'},
                    {'name': 'Leisure and Tourism Management', 'abbreviation': 'LTM'},
                    {'name': 'Nutrition and Dietetics', 'abbreviation': 'NUD'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'School of Information and Communication Technology',
                'abbreviation': 'SICT',
                'departments': [
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                ],
            },
        ],
    },
    {
        'name': 'Abubakar Tatari Ali Polytechnic, Bauchi',
        'abbreviation': 'ATAP',
        'state': 'BAUCHI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Engineering',
                'abbreviation': 'SOE',
                'departments': [
                    {'name': 'Civil Engineering Technology', 'abbreviation': 'CET'},
                    {'name': 'Computer Engineering Technology', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                    {'name': 'Welding and Fabrication', 'abbreviation': 'WAF'},
                ],
            },
            {
                'name': 'School of Environmental Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management and Evaluation', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geological Technology', 'abbreviation': 'GLY'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                    {'name': 'Tourism', 'abbreviation': 'TRM'},
                ],
            },
            {
                'name': 'School of Management Studies',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Cooperative and Economic Management', 'abbreviation': 'CEM'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Insurance', 'abbreviation': 'INS'},
                    {'name': 'Local Government Studies', 'abbreviation': 'LGS'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Purchasing and Supply', 'abbreviation': 'PAS'},
                    {'name': 'Taxation', 'abbreviation': 'TAX'},
                ],
            },
            {
                'name': 'School of General Studies',
                'abbreviation': 'SGS',
                'departments': [
                    {'name': 'Crime Management and Control', 'abbreviation': 'CMC'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Social Development', 'abbreviation': 'SOD'},
                ],
            },
            {
                'name': 'School of Vocational and Technical Education',
                'abbreviation': 'SVTE',
                'departments': [
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Computer and Integrated Science Education', 'abbreviation': 'CIE'},
                    {'name': 'Early Childhood Care and Education', 'abbreviation': 'ECC'},
                    {'name': 'Integrated Science Education', 'abbreviation': 'ISE'},
                    {'name': 'Primary Education', 'abbreviation': 'PRI'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                ],
            },
            {
                'name': 'School of Information and Office Technology Management',
                'abbreviation': 'SIOTM',
                'departments': [
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                ],
            },
        ],
    },
    {
        'name': 'Adamu Tafawa Balewa College of Education, Kangere',
        'abbreviation': 'COEKANGERE',
        'state': 'BAUCHI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'Hausa', 'abbreviation': 'HAU'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISC'},
                    {'name': 'Social Development', 'abbreviation': 'SOD'},
                    {'name': 'Social Studies', 'abbreviation': 'SST'},
                ],
            },
            {
                'name': 'School of Education',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Adult and Non-Formal Education', 'abbreviation': 'ANF'},
                    {'name': 'Early Childhood and Primary Education', 'abbreviation': 'ECP'},
                    {'name': 'Education', 'abbreviation': 'EDN'},
                    {'name': 'Management Studies', 'abbreviation': 'MST'},
                    {'name': 'Nomadic Education', 'abbreviation': 'NOM'},
                ],
            },
            {
                'name': 'School of Science and Vocational Education',
                'abbreviation': 'SSVE',
                'departments': [
                    {'name': 'Agricultural Science Education', 'abbreviation': 'ASE'},
                    {'name': 'Biology Education', 'abbreviation': 'BIE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Chemistry Education', 'abbreviation': 'CHE'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Home Economics', 'abbreviation': 'HEC'},
                    {'name': 'Integrated Science Education', 'abbreviation': 'ISE'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Physics Education', 'abbreviation': 'PYE'},
                ],
            },
        ],
    },
    {
        'name': 'Aminu Saleh College of Education, Azare',
        'abbreviation': 'ASCOEA',
        'state': 'BAUCHI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISC'},
                    {'name': 'Social Studies', 'abbreviation': 'SST'},
                ],
            },
            {
                'name': 'School of Education',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Curriculum Studies', 'abbreviation': 'CUR'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Educational Psychology', 'abbreviation': 'EPY'},
                ],
            },
            {
                'name': 'School of Science and Vocational Education',
                'abbreviation': 'SSVE',
                'departments': [
                    {'name': 'Biology Education', 'abbreviation': 'BIE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Chemistry Education', 'abbreviation': 'CHE'},
                    {'name': 'Home Economics', 'abbreviation': 'HEC'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                ],
            },
        ],
    },
]