# academic_directory/management/commands/state_data/bayelsa.py
"""Universities in Bayelsa State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'Federal University, Otuoke',
        'abbreviation': 'FUOTUOKE',
        'state': 'BAYELSA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Basic Medical Science',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Human Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Human Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Biology Education', 'abbreviation': 'EDB'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Chemistry Education', 'abbreviation': 'EDC'},
                    {'name': 'Computer Science Education', 'abbreviation': 'EDCS'},
                    {'name': 'Economics Education', 'abbreviation': 'EDE'},
                    {'name': 'English Education', 'abbreviation': 'EDEL'},
                    {'name': 'History Education', 'abbreviation': 'EDH'},
                    {'name': 'Mathematics Education', 'abbreviation': 'EDM'},
                    {'name': 'Physics Education', 'abbreviation': 'EDP'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Mechatronics Engineering', 'abbreviation': 'MCE'},
                    {'name': 'Petroleum and Gas Engineering', 'abbreviation': 'PGE'},
                ],
            },
            {
                'name': 'Faculty of Humanities',
                'abbreviation': 'HUM',
                'departments': [
                    {'name': 'English and Communication Studies', 'abbreviation': 'ECS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Journalism and Media Studies', 'abbreviation': 'JMS'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Theatre and Film Studies', 'abbreviation': 'TFS'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Procurement and Logistics Management', 'abbreviation': 'PLM'},
                    {'name': 'Tourism and Hospitality Management', 'abbreviation': 'THM'},
                ],
            },
            {
                'name': 'Faculty of Medical Laboratory Science',
                'abbreviation': 'MLS',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                ],
            },
            {
                'name': 'Faculty of Nursing Science',
                'abbreviation': 'NSG',
                'departments': [
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science and Informatics', 'abbreviation': 'CSI'},
                    {'name': 'Cybersecurity', 'abbreviation': 'CYB'},
                    {'name': 'Environmental Management and Toxicology', 'abbreviation': 'EMT'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Criminology and Security Studies', 'abbreviation': 'CSS'},
                    {'name': 'Economics and Development Studies', 'abbreviation': 'EDS'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Social Work', 'abbreviation': 'SWK'},
                    {'name': 'Sociology and Anthropology', 'abbreviation': 'SOA'},
                ],
            },
        ],
    },
    {
        'name': 'Niger Delta University, Wilberforce Island',
        'abbreviation': 'NDU',
        'state': 'BAYELSA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics', 'abbreviation': 'AEC'},
                    {'name': 'Animal Husbandry', 'abbreviation': 'ANH'},
                    {'name': 'Aquaculture', 'abbreviation': 'AQU'},
                    {'name': 'Crop Production', 'abbreviation': 'CRP'},
                    {'name': 'Fishery', 'abbreviation': 'FIS'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'International Relations and Diplomacy', 'abbreviation': 'IRD'},
                    {'name': 'Literature', 'abbreviation': 'LIT'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Basic Clinical Sciences',
                'abbreviation': 'BCS',
                'departments': [
                    {'name': 'Haematology', 'abbreviation': 'HAE'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Parasitology', 'abbreviation': 'PAR'},
                    {'name': 'Pathology', 'abbreviation': 'PTH'},
                    {'name': 'Pharmacology', 'abbreviation': 'PHC'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Laboratory Techniques', 'abbreviation': 'LBT'},
                    {'name': 'Medicine', 'abbreviation': 'MED'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Surgery', 'abbreviation': 'SUR'},
                ],
            },
            {
                'name': 'Faculty of Clinical Sciences',
                'abbreviation': 'CLM',
                'departments': [
                    {'name': 'Anaesthesiology', 'abbreviation': 'ANE'},
                    {'name': 'Community Health', 'abbreviation': 'CMH'},
                    {'name': 'Medicine', 'abbreviation': 'MED'},
                    {'name': 'Obstetrics and Gynaecology', 'abbreviation': 'OBG'},
                    {'name': 'Paediatrics', 'abbreviation': 'PAE'},
                    {'name': 'Psychiatry and Mental Health', 'abbreviation': 'PMH'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Art Education', 'abbreviation': 'ARE'},
                    {'name': 'Curriculum', 'abbreviation': 'CUR'},
                    {'name': 'Educational Sciences', 'abbreviation': 'EDS'},
                    {'name': 'Humanities and Social Science Education', 'abbreviation': 'HSE'},
                    {'name': 'Information Sciences', 'abbreviation': 'ISC'},
                    {'name': 'Library Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Technology Education', 'abbreviation': 'TED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural Engineering', 'abbreviation': 'AGE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Environmental Engineering', 'abbreviation': 'ENV'},
                    {'name': 'Marine Engineering', 'abbreviation': 'MRE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Petroleum and Gas Engineering', 'abbreviation': 'PGE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building Technologies', 'abbreviation': 'BDT'},
                    {'name': 'Environmental Management', 'abbreviation': 'ENM'},
                    {'name': 'Environmental Studies', 'abbreviation': 'ENS'},
                    {'name': 'Fine Arts', 'abbreviation': 'FIA'},
                    {'name': 'Regional Planning', 'abbreviation': 'RPL'},
                    {'name': 'Surveying and Mapping', 'abbreviation': 'SVM'},
                    {'name': 'Town Planning', 'abbreviation': 'TWP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                    {'name': 'Private Law', 'abbreviation': 'PRL'},
                    {'name': 'Public Law', 'abbreviation': 'PUL'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking', 'abbreviation': 'BNK'},
                    {'name': 'Finance', 'abbreviation': 'FIN'},
                    {'name': 'Information Management', 'abbreviation': 'IFM'},
                    {'name': 'Insurance', 'abbreviation': 'INS'},
                    {'name': 'Management', 'abbreviation': 'MGT'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                ],
            },
            {
                'name': 'Faculty of Nursing Sciences',
                'abbreviation': 'NSG',
                'departments': [
                    {'name': 'Nursing', 'abbreviation': 'NSG'},
                ],
            },
            {
                'name': 'Faculty of Pharmacy',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Applied Chemistry', 'abbreviation': 'APC'},
                    {'name': 'Biotechnology', 'abbreviation': 'BTC'},
                    {'name': 'Herbalism', 'abbreviation': 'HER'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Pharmacology', 'abbreviation': 'PHC'},
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                    {'name': 'Toxicology', 'abbreviation': 'TOX'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biological and Life Sciences', 'abbreviation': 'BLS'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Environmental Studies', 'abbreviation': 'ENS'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Sciences', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of General Studies',
                'abbreviation': 'GST',
                'departments': [
                    {'name': 'Arts and Humanities', 'abbreviation': 'ARH'},
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'Natural Sciences', 'abbreviation': 'NSC'},
                    {'name': 'Social Sciences', 'abbreviation': 'SSC'},
                ],
            },
        ],
    },
    {
        'name': 'University of Africa, Toru-Orua',
        'abbreviation': 'UAT',
        'state': 'BAYELSA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension Services', 'abbreviation': 'AEC'},
                    {'name': 'Animal Production and Health', 'abbreviation': 'APH'},
                    {'name': 'Crop, Soil and Pest Management', 'abbreviation': 'CSP'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Tourism and Hotel Management', 'abbreviation': 'THM'},
                ],
            },
            {
                'name': 'Faculty of Basic and Applied Sciences',
                'abbreviation': 'BAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Arts and Education',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics and African Languages', 'abbreviation': 'LIN'},
                    {'name': 'Theater Arts', 'abbreviation': 'THA'},
                    {'name': 'Educational Management', 'abbreviation': 'EDM'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                ],
            },
            {
                'name': 'Faculty of Social and Management Sciences',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Industrial Relations and Personnel Management', 'abbreviation': 'IRP'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Ekowe',
        'abbreviation': 'FEDPOEKO',
        'state': 'BAYELSA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Agricultural Technology',
                'abbreviation': 'SAT',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGR'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Electrical/Electronic Engineering Technology', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Management Science',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Local Government Studies', 'abbreviation': 'LGS'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Bayelsa State Polytechnic, Aleibiri',
        'abbreviation': 'BYSPOLY',
        'state': 'BAYELSA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering Technology', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronics Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                ],
            },
        ],
    },
    {
        'name': 'Isaac Jasper Boro College of Education, Sagbama',
        'abbreviation': 'IJBCOE',
        'state': 'BAYELSA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Education',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Curriculum and Instruction', 'abbreviation': 'CUI'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Educational Psychology', 'abbreviation': 'EPY'},
                ],
            },
            {
                'name': 'School of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Social Studies', 'abbreviation': 'SST'},
                ],
            },
            {
                'name': 'School of Science and Vocational Education',
                'abbreviation': 'SSVE',
                'departments': [
                    {'name': 'Agricultural Science', 'abbreviation': 'AGR'},
                    {'name': 'Biology/Integrated Science', 'abbreviation': 'BIS'},
                    {'name': 'Biology/Mathematics', 'abbreviation': 'BMA'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Chemistry/Integrated Science', 'abbreviation': 'CIS'},
                    {'name': 'Chemistry/Mathematics', 'abbreviation': 'CMA'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Home Economics', 'abbreviation': 'HEC'},
                    {'name': 'Integrated Science', 'abbreviation': 'ISC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Physics Education', 'abbreviation': 'PYE'},
                ],
            },
        ],
    },
]