# academic_directory/management/commands/state_data/cross_river.py
"""Universities in Cross River State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'University of Calabar',
        'abbreviation': 'UNICAL',
        'state': 'CROSS_RIVER',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Agriculture, Forestry and Wildlife Resources Management',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Agricultural Extension and Rural Sociology', 'abbreviation': 'AEX'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Forestry and Wildlife Resources Management', 'abbreviation': 'FWL'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Allied Medical Sciences',
                'abbreviation': 'AMS',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                    {'name': 'Radiography and Radiological Sciences', 'abbreviation': 'RAD'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics and Nigerian Languages', 'abbreviation': 'LIN'},
                    {'name': 'Modern Languages and Translation Studies', 'abbreviation': 'MLT'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Religious and Cultural Studies', 'abbreviation': 'RCS'},
                    {'name': 'Theatre and Media Studies', 'abbreviation': 'TMS'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomical Sciences', 'abbreviation': 'ANA'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Pharmacology', 'abbreviation': 'PHC'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Biological Sciences',
                'abbreviation': 'BIO',
                'departments': [
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Genetics and Biotechnology', 'abbreviation': 'GNB'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Plant and Ecological Studies', 'abbreviation': 'PES'},
                    {'name': 'Zoology and Environmental Biology', 'abbreviation': 'ZEB'},
                ],
            },
            {
                'name': 'Faculty of Clinical Sciences',
                'abbreviation': 'CLM',
                'departments': [
                    {'name': 'Anaesthesiology', 'abbreviation': 'ANE'},
                    {'name': 'Chemical Pathology', 'abbreviation': 'CHP'},
                    {'name': 'Community Medicine', 'abbreviation': 'CMH'},
                    {'name': 'Dentistry', 'abbreviation': 'DEN'},
                    {'name': 'Family Medicine', 'abbreviation': 'FAM'},
                    {'name': 'Haematology', 'abbreviation': 'HAE'},
                    {'name': 'Histopathology', 'abbreviation': 'HIS'},
                    {'name': 'Medical Microbiology and Parasitology', 'abbreviation': 'MMP'},
                    {'name': 'Medicine', 'abbreviation': 'MED'},
                    {'name': 'Obstetrics and Gynaecology', 'abbreviation': 'OBG'},
                    {'name': 'Orthopaedic and Trauma Surgery', 'abbreviation': 'OTS'},
                    {'name': 'Otorhinolaryngology', 'abbreviation': 'ENT'},
                    {'name': 'Paediatrics', 'abbreviation': 'PAE'},
                    {'name': 'Psychiatry', 'abbreviation': 'PSY'},
                    {'name': 'Radiology', 'abbreviation': 'RAD'},
                    {'name': 'Surgery', 'abbreviation': 'SUR'},
                    {'name': 'Urology', 'abbreviation': 'URO'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Adult and Continuing Education', 'abbreviation': 'ACE'},
                    {'name': 'Arts and Social Science Education', 'abbreviation': 'ASE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Continuing Education and Development Studies', 'abbreviation': 'CED'},
                    {'name': 'Curriculum and Teaching', 'abbreviation': 'CUR'},
                    {'name': 'Educational Administration and Planning', 'abbreviation': 'EAP'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Environmental Education', 'abbreviation': 'ENE'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Human Kinetics and Health Education', 'abbreviation': 'HKE'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Social Science Education', 'abbreviation': 'SSE'},
                    {'name': 'Special Education', 'abbreviation': 'SPE'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Science',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Environmental Resource Management', 'abbreviation': 'ERM'},
                    {'name': 'Geography and Environmental Science', 'abbreviation': 'GEO'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Management', 'abbreviation': 'BUM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Medical Laboratory Science',
                'abbreviation': 'MLS',
                'departments': [
                    {'name': 'Bacteriology, Virology and Mycology', 'abbreviation': 'BVM'},
                    {'name': 'Chemical Pathology', 'abbreviation': 'CHP'},
                    {'name': 'Haematology and Blood Transfusion Science', 'abbreviation': 'HBT'},
                    {'name': 'Histopathology and Cytology', 'abbreviation': 'HPC'},
                    {'name': 'Medical Parasitology and Entomology', 'abbreviation': 'MPE'},
                ],
            },
            {
                'name': 'Faculty of Oceanography',
                'abbreviation': 'OCE',
                'departments': [
                    {'name': 'Biological Oceanography', 'abbreviation': 'BIO'},
                    {'name': 'Chemical Oceanography', 'abbreviation': 'CHO'},
                    {'name': 'Geological Oceanography', 'abbreviation': 'GEO'},
                    {'name': 'Mariculture and Marine Fisheries Resources', 'abbreviation': 'MMF'},
                    {'name': 'Physical Oceanography', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Physical Sciences',
                'abbreviation': 'PSC',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Pure and Applied Chemistry', 'abbreviation': 'PAC'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Geography and Environmental Science', 'abbreviation': 'GEO'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Social Work', 'abbreviation': 'SWK'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
        ],
    },
    {
        'name': 'University of Cross River State',
        'abbreviation': 'UNICROSS',
        'state': 'CROSS_RIVER',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture and Forestry',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Agronomy', 'abbreviation': 'AGN'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Fishery and Aquatic Sciences', 'abbreviation': 'FIS'},
                    {'name': 'Forestry and Wildlife Management', 'abbreviation': 'FWL'},
                ],
            },
            {
                'name': 'Faculty of Architecture',
                'abbreviation': 'ARC',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Human Anatomy and Forensic Anthropology', 'abbreviation': 'ANA'},
                    {'name': 'Human Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Medical Biochemistry', 'abbreviation': 'BCH'},
                ],
            },
            {
                'name': 'Faculty of Biological Sciences',
                'abbreviation': 'BIO',
                'departments': [
                    {'name': 'Animal Health and Environmental Biology', 'abbreviation': 'AEB'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Plant Science and Biotechnology', 'abbreviation': 'PSB'},
                ],
            },
            {
                'name': 'Faculty of Communication and Media Studies',
                'abbreviation': 'CMS',
                'departments': [
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Curriculum and Instructional Technology', 'abbreviation': 'CIT'},
                    {'name': 'Educational Foundations and Administration', 'abbreviation': 'EFA'},
                    {'name': 'Educational Management', 'abbreviation': 'EDM'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Human Kinetics and Health Education', 'abbreviation': 'HKE'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Vocational and Technical Education', 'abbreviation': 'VTE'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical/Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Wood Product Engineering', 'abbreviation': 'WPE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Science',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                    {'name': 'Visual Arts and Technology', 'abbreviation': 'VAT'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Hospitality and Tourism', 'abbreviation': 'HTM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                ],
            },
            {
                'name': 'Faculty of Physical Sciences',
                'abbreviation': 'PSC',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics and Statistics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
        ],
    },
    {
        'name': 'Arthur Jarvis University, Akpabuyo',
        'abbreviation': 'AJU',
        'state': 'CROSS_RIVER',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Plant Science and Biotechnology', 'abbreviation': 'PSB'},
                ],
            },
            {
                'name': 'Faculty of Humanities, Management and Social Sciences',
                'abbreviation': 'HMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Criminology and Security Studies', 'abbreviation': 'CSS'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Entrepreneurial Studies', 'abbreviation': 'ENT'},
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'Hospitality and Tourism Management', 'abbreviation': 'HTM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Peace and Conflict Resolution', 'abbreviation': 'PCR'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Human Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Human Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Optometry', 'abbreviation': 'OPT'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Early Childhood Care Education', 'abbreviation': 'ECC'},
                    {'name': 'Education/Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education/Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education/Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education/Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education/Political Science', 'abbreviation': 'EDPS'},
                    {'name': 'Educational Management', 'abbreviation': 'EDM'},
                    {'name': 'Educational Technology', 'abbreviation': 'EDT'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Primary Education', 'abbreviation': 'PRI'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Ugep',
        'abbreviation': 'FEDPOLYUGE',
        'state': 'CROSS_RIVER',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Nogak Polytechnic, Ikom',
        'abbreviation': 'NOGAK',
        'state': 'CROSS_RIVER',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Cross River State College of Education, Akamkpa',
        'abbreviation': 'CRSCOED',
        'state': 'CROSS_RIVER',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISC'},
                    {'name': 'Social Studies', 'abbreviation': 'SST'},
                ],
            },
            {
                'name': 'School of Education',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Agricultural Science Education', 'abbreviation': 'ASE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Curriculum and Instruction', 'abbreviation': 'CUI'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Human Kinetics and Health Education', 'abbreviation': 'HKE'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'School of Science and Vocational Education',
                'abbreviation': 'SSVE',
                'departments': [
                    {'name': 'Biology Education', 'abbreviation': 'BIE'},
                    {'name': 'Chemistry Education', 'abbreviation': 'CHE'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Home Economics', 'abbreviation': 'HEC'},
                    {'name': 'Integrated Science Education', 'abbreviation': 'ISE'},
                    {'name': 'Mathematics Education', 'abbreviation': 'MTE'},
                    {'name': 'Physics Education', 'abbreviation': 'PYE'},
                ],
            },
        ],
    },
]