# academic_directory/management/commands/state_data/delta.py
"""Universities in Delta State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'Federal University of Petroleum Resources, Effurun',
        'abbreviation': 'FUPRE',
        'state': 'DELTA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'College of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Chemical and Petroleum Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Marine Engineering', 'abbreviation': 'MRE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Natural Gas Engineering', 'abbreviation': 'NGE'},
                    {'name': 'Petrochemical Engineering', 'abbreviation': 'PCE'},
                    {'name': 'Petroleum Engineering', 'abbreviation': 'PET'},
                ],
            },
            {
                'name': 'College of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Earth Sciences', 'abbreviation': 'ESC'},
                    {'name': 'Environmental Management and Toxicology', 'abbreviation': 'EMT'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'College of Technology',
                'abbreviation': 'TEC',
                'departments': [
                    {'name': 'Environmental Technology', 'abbreviation': 'ENT'},
                ],
            },
        ],
    },
    {
        'name': 'Delta State University, Abraka',
        'abbreviation': 'DELSU',
        'state': 'DELTA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics', 'abbreviation': 'AEC'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Fisheries', 'abbreviation': 'FIS'},
                    {'name': 'Forestry and Wildlife', 'abbreviation': 'FWL'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Clinical Sciences',
                'abbreviation': 'CLM',
                'departments': [
                    {'name': 'Anaesthesiology', 'abbreviation': 'ANE'},
                    {'name': 'Chemical Pathology', 'abbreviation': 'CHP'},
                    {'name': 'Community Medicine', 'abbreviation': 'CMH'},
                    {'name': 'Dentistry', 'abbreviation': 'DEN'},
                    {'name': 'Family Medicine', 'abbreviation': 'FAM'},
                    {'name': 'Haematology', 'abbreviation': 'HAE'},
                    {'name': 'Histopathology', 'abbreviation': 'HIS'},
                    {'name': 'Medical Microbiology and Parasitology', 'abbreviation': 'MMP'},
                    {'name': 'Medicine', 'abbreviation': 'MED'},
                    {'name': 'Obstetrics and Gynaecology', 'abbreviation': 'OBG'},
                    {'name': 'Orthopaedic and Trauma Surgery', 'abbreviation': 'OTS'},
                    {'name': 'Otorhinolaryngology', 'abbreviation': 'ENT'},
                    {'name': 'Paediatrics', 'abbreviation': 'PAE'},
                    {'name': 'Psychiatry', 'abbreviation': 'PSY'},
                    {'name': 'Radiology', 'abbreviation': 'RAD'},
                    {'name': 'Surgery', 'abbreviation': 'SUR'},
                    {'name': 'Urology', 'abbreviation': 'URO'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Adult and Continuing Education', 'abbreviation': 'ACE'},
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Curriculum and Instruction', 'abbreviation': 'CUI'},
                    {'name': 'Educational Administration and Planning', 'abbreviation': 'EAP'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Educational Psychology', 'abbreviation': 'EPY'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Health Education', 'abbreviation': 'HED'},
                    {'name': 'Human Kinetics', 'abbreviation': 'HKI'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Social Science Education', 'abbreviation': 'SSE'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural Engineering', 'abbreviation': 'AGE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Studies',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Geography and Regional Planning', 'abbreviation': 'GRP'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Commercial Law', 'abbreviation': 'COM'},
                    {'name': 'International Law and Jurisprudence', 'abbreviation': 'ILJ'},
                    {'name': 'Private Law', 'abbreviation': 'PRL'},
                    {'name': 'Public Law', 'abbreviation': 'PUL'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                ],
            },
            {
                'name': 'Faculty of Pharmacy',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Clinical Pharmacy and Pharmacy Administration', 'abbreviation': 'CPA'},
                    {'name': 'Pharmaceutical Chemistry', 'abbreviation': 'PHC'},
                    {'name': 'Pharmaceutical Microbiology', 'abbreviation': 'PHM'},
                    {'name': 'Pharmaceutical Technology and Industrial Pharmacy', 'abbreviation': 'PTI'},
                    {'name': 'Pharmacognosy and Environmental Medicines', 'abbreviation': 'PEM'},
                    {'name': 'Pharmacology and Toxicology', 'abbreviation': 'PHT'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Animal and Environmental Biology', 'abbreviation': 'AEB'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
        ],
    },
    {
        'name': 'Dennis Osadebay University, Asaba',
        'abbreviation': 'DOU',
        'state': 'DELTA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics', 'abbreviation': 'AEC'},
                    {'name': 'Agricultural Extension', 'abbreviation': 'AEX'},
                    {'name': 'Animal Production', 'abbreviation': 'ANP'},
                    {'name': 'Crop Science/Soil Science', 'abbreviation': 'CSS'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'CMP',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Management', 'abbreviation': 'BUM'},
                    {'name': 'Criminology and Security Studies', 'abbreviation': 'CSS'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'International Relations', 'abbreviation': 'INT'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Environmental Management and Toxicology', 'abbreviation': 'EMT'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Home Science', 'abbreviation': 'HSC'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Plant Science and Biotechnology', 'abbreviation': 'PSB'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Delta State University of Science and Technology, Ozoro',
        'abbreviation': 'DSUST',
        'state': 'DELTA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGR'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Fisheries', 'abbreviation': 'FIS'},
                    {'name': 'Forestry and Wildlife', 'abbreviation': 'FWL'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts and Humanities',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'CMP',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'University of Delta, Agbor',
        'abbreviation': 'UNIDEL',
        'state': 'DELTA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Fisheries', 'abbreviation': 'FIS'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'CMP',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Western Delta University, Oghara',
        'abbreviation': 'WDU',
        'state': 'DELTA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'College of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Basic and Industrial Chemistry', 'abbreviation': 'BIC'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Geology and Petroleum Studies', 'abbreviation': 'GPS'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Mathematics and Computer Science', 'abbreviation': 'MCS'},
                    {'name': 'Microbiology and Biotechnology', 'abbreviation': 'MCB'},
                    {'name': 'Plant Science and Microbiology', 'abbreviation': 'PSM'},
                    {'name': 'Physics and Electronics', 'abbreviation': 'PHE'},
                    {'name': 'Physics and Energy Studies', 'abbreviation': 'PES'},
                    {'name': 'Pure and Industrial Mathematics', 'abbreviation': 'PIM'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                ],
            },
            {
                'name': 'College of Social and Management Sciences',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Hotel and Tourism Management', 'abbreviation': 'HTM'},
                    {'name': 'International Relations', 'abbreviation': 'INT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science and Public Administration', 'abbreviation': 'PPA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'College of Applied Health Sciences',
                'abbreviation': 'AHS',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                ],
            },
            {
                'name': 'College of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'College of Computing',
                'abbreviation': 'CMP',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                ],
            },
            {
                'name': 'College of Postgraduate Studies',
                'abbreviation': 'PGS',
                'departments': [],
            },
        ],
    },
    {
        'name': 'Novena University, Ogume-Amai',
        'abbreviation': 'NOVENA',
        'state': 'DELTA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Arts and Humanities',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'International Relations', 'abbreviation': 'INT'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Education', 'abbreviation': 'EDN'},
                ],
            },
        ],
    },
    {
        'name': 'Michael and Cecilia Ibru University, Agbara-Otor',
        'abbreviation': 'MCIU',
        'state': 'DELTA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Arts and Humanities',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'CMP',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Science',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Natural and Applied Science',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Applied Biology', 'abbreviation': 'APB'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biotechnology', 'abbreviation': 'BTC'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Environmental Management and Toxicology', 'abbreviation': 'EMT'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Industrial Mathematics', 'abbreviation': 'IMT'},
                    {'name': 'Industrial Physics', 'abbreviation': 'IPH'},
                ],
            },
        ],
    },
    {
        'name': 'Edwin Clark University, Kiagbodo',
        'abbreviation': 'ECU',
        'state': 'DELTA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Agricultural Sciences',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                    {'name': 'Aquaculture and Fisheries', 'abbreviation': 'AQU'},
                    {'name': 'Forestry and Wildlife', 'abbreviation': 'FWL'},
                    {'name': 'Hotel Management and Tourism', 'abbreviation': 'HMT'},
                ],
            },
            {
                'name': 'Faculty of Humanities, Social and Management Sciences',
                'abbreviation': 'HMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
        ],
    },
    {
        'name': 'Admiralty University of Nigeria, Ibusa',
        'abbreviation': 'ADUN',
        'state': 'DELTA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Applied Physics and Renewable Energy', 'abbreviation': 'APRE'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Conservation and Environmental Biology', 'abbreviation': 'CEB'},
                    {'name': 'Forensic Science', 'abbreviation': 'FRS'},
                    {'name': 'Industrial Mathematics', 'abbreviation': 'IMT'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Social and Management Sciences',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Hospitality and Tourism Studies', 'abbreviation': 'HTM'},
                    {'name': 'International Relations', 'abbreviation': 'INT'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'CMP',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                ],
            },
        ],
    },
    {
        'name': 'Eagle Heights University, Omadino, Warri',
        'abbreviation': 'EHU',
        'state': 'DELTA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Science and Technology',
                'abbreviation': 'SCT',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Orogun',
        'abbreviation': 'FEDPOLYOROGUN',
        'state': 'DELTA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                ],
            },
            {
                'name': 'School of Environmental Design',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Petroleum Training Institute, Effurun',
        'abbreviation': 'PTI',
        'state': 'DELTA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Electrical/Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                    {'name': 'Mineral and Petroleum Resources Engineering Technology', 'abbreviation': 'MPE'},
                    {'name': 'Petroleum Engineering Technology', 'abbreviation': 'PET'},
                    {'name': 'Welding and Fabrication Technology', 'abbreviation': 'WFT'},
                ],
            },
            {
                'name': 'School of Industrial Safety and Environmental Engineering',
                'abbreviation': 'SIEE',
                'departments': [
                    {'name': 'Industrial Safety and Environmental Engineering Technology', 'abbreviation': 'IEE'},
                ],
            },
            {
                'name': 'School of Petroleum and Gas Processing',
                'abbreviation': 'SPGP',
                'departments': [
                    {'name': 'Petroleum and Gas Processing', 'abbreviation': 'PGP'},
                ],
            },
            {
                'name': 'School of Computing and Information Technology',
                'abbreviation': 'SCIT',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                ],
            },
            {
                'name': 'School of Science Laboratory Technology',
                'abbreviation': 'SSLT',
                'departments': [
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                ],
            },
            {
                'name': 'School of Business Studies',
                'abbreviation': 'SBS',
                'departments': [
                    {'name': 'Petroleum Marketing and Business Studies', 'abbreviation': 'PMB'},
                ],
            },
        ],
    },
    {
        'name': 'Delta State Polytechnic, Otefe-Oghara',
        'abbreviation': 'DESPO',
        'state': 'DELTA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Industrial Maintenance Engineering Technology', 'abbreviation': 'IME'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                    {'name': 'Welding and Fabrication Technology', 'abbreviation': 'WFT'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Delta State Polytechnic, Ogwashi-Uku',
        'abbreviation': 'OGWASHIPOLY',
        'state': 'DELTA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Agricultural Engineering Technology', 'abbreviation': 'AET'},
                    {'name': 'Civil Engineering Technology', 'abbreviation': 'CET'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                ],
            },
            {
                'name': 'School of Environmental Design',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Delta State School of Marine Technology, Burutu',
        'abbreviation': 'DESOMATECH',
        'state': 'DELTA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Marine Engineering',
                'abbreviation': 'SME',
                'departments': [
                    {'name': 'Marine Engineering Technology', 'abbreviation': 'MRE'},
                    {'name': 'Naval Architecture and Shipbuilding', 'abbreviation': 'NAS'},
                ],
            },
            {
                'name': 'School of Maritime Transport',
                'abbreviation': 'SMT',
                'departments': [
                    {'name': 'Maritime Transport and Business Studies', 'abbreviation': 'MTB'},
                    {'name': 'Nautical Science', 'abbreviation': 'NAU'},
                ],
            },
            {
                'name': 'School of Fisheries and Aquaculture',
                'abbreviation': 'SFA',
                'departments': [
                    {'name': 'Fisheries Technology', 'abbreviation': 'FIS'},
                    {'name': 'Aquaculture Technology', 'abbreviation': 'AQU'},
                ],
            },
        ],
    },
    {
        'name': 'Calvary Polytechnic, Owa-Oyibo',
        'abbreviation': 'CALVARYPOLY',
        'state': 'DELTA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Bellmark Polytechnic, Kwale',
        'abbreviation': 'BELLMARK',
        'state': 'DELTA',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
]