# academic_directory/management/commands/state_data/ebonyi.py
"""Universities in Ebonyi State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'Alex Ekwueme Federal University, Ndufu-Alike',
        'abbreviation': 'FUNAI',
        'state': 'EBONYI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'College of Medical Sciences',
                'abbreviation': 'CMS',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Agribusiness and Management', 'abbreviation': 'ABM'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Biological Science',
                'abbreviation': 'BIO',
                'departments': [
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Biotechnology', 'abbreviation': 'BTC'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education and Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education and English Language', 'abbreviation': 'EDEL'},
                    {'name': 'Education and Geography', 'abbreviation': 'EDG'},
                    {'name': 'Education and Integrated Science', 'abbreviation': 'EDIS'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Social Studies Education', 'abbreviation': 'SSE'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Engineering and Technology',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Information Engineering', 'abbreviation': 'EIE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Computer Science and Informatics', 'abbreviation': 'CSI'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Environmental Management', 'abbreviation': 'ENM'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Humanities',
                'abbreviation': 'HUM',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Physical Science',
                'abbreviation': 'PSC',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Sociology and Anthropology', 'abbreviation': 'SOA'},
                ],
            },
        ],
    },
    {
        'name': 'Ebonyi State University, Abakaliki',
        'abbreviation': 'EBSU',
        'state': 'EBONYI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture and Natural Resource Management',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Fishery and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Food Science and Technology', 'abbreviation': 'FST'},
                    {'name': 'Soil Science and Environmental Management', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English Language and Literature', 'abbreviation': 'ELL'},
                    {'name': 'History and International Relations', 'abbreviation': 'HIR'},
                    {'name': 'Igbo, African and Asian Studies', 'abbreviation': 'IAS'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Theatre and Film Studies', 'abbreviation': 'TFS'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Clinical Medicine',
                'abbreviation': 'CLM',
                'departments': [
                    {'name': 'Community Medicine', 'abbreviation': 'CMH'},
                    {'name': 'Internal Medicine', 'abbreviation': 'INT'},
                    {'name': 'Pharmacology', 'abbreviation': 'PHC'},
                    {'name': 'Surgery', 'abbreviation': 'SUR'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Adult Education', 'abbreviation': 'ADE'},
                    {'name': 'Arts/Social Science Education', 'abbreviation': 'ASE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Home Economics', 'abbreviation': 'HEC'},
                    {'name': 'Human Kinetic and Health Education', 'abbreviation': 'HKE'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Technology and Vocational Education', 'abbreviation': 'TVE'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural and Bioresources Engineering', 'abbreviation': 'ABE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Petroleum Engineering', 'abbreviation': 'PET'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                    {'name': 'Geography and Environmental Science', 'abbreviation': 'GES'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Health Science and Technology',
                'abbreviation': 'HST',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Business Law', 'abbreviation': 'BUL'},
                    {'name': 'Civil Law', 'abbreviation': 'CLL'},
                    {'name': 'International Law and Jurisprudence', 'abbreviation': 'ILJ'},
                    {'name': 'Private and Property Law', 'abbreviation': 'PPL'},
                    {'name': 'Public Law', 'abbreviation': 'PUL'},
                ],
            },
            {
                'name': 'Faculty of Management Science',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Management', 'abbreviation': 'BUM'},
                    {'name': 'Cooperative Economics and Management', 'abbreviation': 'CEM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Natural Sciences',
                'abbreviation': 'NAT',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biological Sciences', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Pharmaceutical Sciences',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Clinical Pharmacy and Pharmacy Practice', 'abbreviation': 'CPP'},
                    {'name': 'Pharmaceutical Chemistry', 'abbreviation': 'PHC'},
                    {'name': 'Pharmaceutical Microbiology and Biotechnology', 'abbreviation': 'PMB'},
                    {'name': 'Pharmacology and Toxicology', 'abbreviation': 'PHT'},
                    {'name': 'Pharmaceutics and Pharmaceutical Technology', 'abbreviation': 'PPT'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Applied Biology', 'abbreviation': 'APB'},
                    {'name': 'Applied Microbiology', 'abbreviation': 'APM'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biotechnology', 'abbreviation': 'BTC'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology/Exploration', 'abbreviation': 'GLY'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Industrial Mathematics and Statistics', 'abbreviation': 'IMS'},
                    {'name': 'Industrial Physics', 'abbreviation': 'IPH'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences and Humanities',
                'abbreviation': 'SSH',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'English Language/Literature', 'abbreviation': 'ELL'},
                    {'name': 'History and International Relations', 'abbreviation': 'HIR'},
                    {'name': 'Language and Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Philosophy and Religion', 'abbreviation': 'PHR'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Social Works', 'abbreviation': 'SWK'},
                    {'name': 'Sociology and Anthropology', 'abbreviation': 'SOA'},
                ],
            },
        ],
    },
    {
        'name': 'David Umahi Federal University of Health Sciences, Uburu',
        'abbreviation': 'DUFUHS',
        'state': 'EBONYI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'College of Medicine',
                'abbreviation': 'MED',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                ],
            },
            {
                'name': 'Faculty of Pharmacy',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'Faculty of Dentistry',
                'abbreviation': 'DEN',
                'departments': [
                    {'name': 'Dentistry and Dental Surgery', 'abbreviation': 'DDS'},
                ],
            },
            {
                'name': 'Faculty of Allied Health Sciences',
                'abbreviation': 'AHS',
                'departments': [
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Physiotherapy', 'abbreviation': 'PTP'},
                    {'name': 'Radiography and Radiation Science', 'abbreviation': 'RAD'},
                    {'name': 'Optometry', 'abbreviation': 'OPT'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                    {'name': 'Human Nutrition and Dietetics', 'abbreviation': 'HND'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Biology/Biotechnology', 'abbreviation': 'BTC'},
                    {'name': 'Microbiology/Parasitology', 'abbreviation': 'MCP'},
                    {'name': 'Industrial and Medical Physics', 'abbreviation': 'IMP'},
                    {'name': 'Industrial and Medicinal Chemistry', 'abbreviation': 'IMC'},
                    {'name': 'Industrial Mathematics and Statistics', 'abbreviation': 'IMS'},
                ],
            },
            {
                'name': 'Faculty of Biomedical Engineering',
                'abbreviation': 'BME',
                'departments': [
                    {'name': 'Biomedical Engineering', 'abbreviation': 'BME'},
                ],
            },
        ],
    },
    {
        'name': 'Akanu Ibiam Federal Polytechnic, Unwana',
        'abbreviation': 'AKANUPOLY',
        'state': 'EBONYI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Business Studies',
                'abbreviation': 'SBS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Civil Engineering Technology', 'abbreviation': 'CET'},
                    {'name': 'Computer Engineering Technology', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronics Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                    {'name': 'Mechatronics Engineering Technology', 'abbreviation': 'MCE'},
                    {'name': 'Metallurgical Engineering Technology', 'abbreviation': 'MTE'},
                ],
            },
            {
                'name': 'School of Environmental Design and Valuations',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Ceramics Technology', 'abbreviation': 'CER'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Horticulture and Landscaping', 'abbreviation': 'HOR'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'School of Industrial Technology',
                'abbreviation': 'SIT',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGR'},
                    {'name': 'Animal Production Technology', 'abbreviation': 'APT'},
                    {'name': 'Ceramics and Glass Technology', 'abbreviation': 'CGT'},
                    {'name': 'Food Technology', 'abbreviation': 'FST'},
                    {'name': 'Horticulture and Landscape Technology', 'abbreviation': 'HLT'},
                    {'name': 'Hospitality Management and Tourism', 'abbreviation': 'HMT'},
                ],
            },
            {
                'name': 'School of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics and Statistics', 'abbreviation': 'MTH'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                ],
            },
            {
                'name': 'School of General and Basic Studies',
                'abbreviation': 'SGB',
                'departments': [
                    {'name': 'Continuing Education', 'abbreviation': 'CED'},
                    {'name': 'General Studies', 'abbreviation': 'GST'},
                    {'name': 'Languages', 'abbreviation': 'LAN'},
                    {'name': 'Legal Studies', 'abbreviation': 'LEG'},
                    {'name': 'Remedial Studies', 'abbreviation': 'REM'},
                    {'name': 'Social Science', 'abbreviation': 'SOC'},
                ],
            },
        ],
    },
    {
        'name': 'Federal College of Agriculture, Ishiagu',
        'abbreviation': 'FCAI',
        'state': 'EBONYI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Agricultural Technology',
                'abbreviation': 'SAT',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGR'},
                    {'name': 'Animal Health and Production Technology', 'abbreviation': 'AHP'},
                    {'name': 'Horticultural Technology', 'abbreviation': 'HOR'},
                ],
            },
            {
                'name': 'School of Applied Agriculture and Management Technology',
                'abbreviation': 'SAAMT',
                'departments': [
                    {'name': 'Agricultural Extension and Management', 'abbreviation': 'AEM'},
                    {'name': 'Cooperative Economics and Management', 'abbreviation': 'CEM'},
                    {'name': 'Pest Management Technology', 'abbreviation': 'PMT'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Agricultural and Bio-Environmental Engineering Technology', 'abbreviation': 'ABE'},
                    {'name': 'Computer Science Technology', 'abbreviation': 'CST'},
                ],
            },
            {
                'name': 'School of Management Technology',
                'abbreviation': 'SMT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
        ],
    },
    {
        'name': 'Ebonyi State College of Education, Ikwo',
        'abbreviation': 'EBSCOED',
        'state': 'EBONYI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISC'},
                    {'name': 'Social Studies', 'abbreviation': 'SST'},
                ],
            },
            {
                'name': 'School of Education',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Agricultural Science', 'abbreviation': 'AGR'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Curriculum and Instruction', 'abbreviation': 'CUI'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'School of Science and Vocational Education',
                'abbreviation': 'SSVE',
                'departments': [
                    {'name': 'Biology/Chemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology/Geography', 'abbreviation': 'BGE'},
                    {'name': 'Chemistry/Mathematics', 'abbreviation': 'CMA'},
                    {'name': 'Chemistry/Physics', 'abbreviation': 'CPH'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Integrated Science', 'abbreviation': 'ISC'},
                    {'name': 'Mathematics/Physics', 'abbreviation': 'MPH'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                ],
            },
        ],
    },
]