# academic_directory/management/commands/state_data/edo.py
"""Universities in Edo State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'University of Benin',
        'abbreviation': 'UNIBEN',
        'state': 'EDO',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension Services', 'abbreviation': 'AEC'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Aquaculture and Fisheries Management', 'abbreviation': 'FIS'},
                    {'name': 'Food Science and Nutrition', 'abbreviation': 'FST'},
                    {'name': 'Forestry and Wildlife', 'abbreviation': 'FWL'},
                    {'name': 'Forest Resources and Wildlife Management', 'abbreviation': 'FRW'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literature', 'abbreviation': 'ELL'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'Linguistics/Edo Language', 'abbreviation': 'LED'},
                    {'name': 'Linguistics/Igbo Language', 'abbreviation': 'LIG'},
                    {'name': 'Linguistics Studies', 'abbreviation': 'LIN'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'International Studies and Diplomacy', 'abbreviation': 'ISD'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                    {'name': 'Fine and Applied Arts', 'abbreviation': 'FAA'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Medical Biochemistry', 'abbreviation': 'MBX'},
                    {'name': 'Medical Laboratory Sciences', 'abbreviation': 'MLS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Physiotherapy', 'abbreviation': 'PTP'},
                    {'name': 'Radiography and Radiation Science', 'abbreviation': 'RAD'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'CMP',
                'departments': [
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Data Science', 'abbreviation': 'DSC'},
                    {'name': 'Information and Communication Technology', 'abbreviation': 'ICT'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                ],
            },
            {
                'name': 'Faculty of Dentistry',
                'abbreviation': 'DEN',
                'departments': [
                    {'name': 'Dentistry', 'abbreviation': 'DEN'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Linguistics/Edo Education', 'abbreviation': 'LED'},
                    {'name': 'Linguistics/Igbo Education', 'abbreviation': 'LIG'},
                    {'name': 'English and Literature Education', 'abbreviation': 'ELE'},
                    {'name': 'Early Childhood Education', 'abbreviation': 'ECC'},
                    {'name': 'Adult and Non-formal Education', 'abbreviation': 'ANF'},
                    {'name': 'Adult Education Fine Arts', 'abbreviation': 'AFA'},
                    {'name': 'Adult Education English and Literature', 'abbreviation': 'AEL'},
                    {'name': 'Adult Education Political Science', 'abbreviation': 'APS'},
                    {'name': 'Adult Education Economics', 'abbreviation': 'AEC'},
                    {'name': 'Adult Education Geography and Regional Planning', 'abbreviation': 'AGP'},
                    {'name': 'Special Education', 'abbreviation': 'SPE'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Education Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education Integrated Science', 'abbreviation': 'EDIS'},
                    {'name': 'Education Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education Physics', 'abbreviation': 'EDP'},
                    {'name': 'Education Social Studies', 'abbreviation': 'EDSS'},
                    {'name': 'Education Geography', 'abbreviation': 'EDG'},
                    {'name': 'Education Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education Physical Education', 'abbreviation': 'EDPE'},
                    {'name': 'Education Educational Administration', 'abbreviation': 'EDA'},
                    {'name': 'Education Management', 'abbreviation': 'EDM'},
                    {'name': 'Education Political Science and Public Administration', 'abbreviation': 'EDPS'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Sports Science and Human Performance', 'abbreviation': 'SSP'},
                    {'name': 'Sports Coaching and Management', 'abbreviation': 'SCM'},
                    {'name': 'Human Kinetics and Sports Development', 'abbreviation': 'HKD'},
                    {'name': 'Environmental Education', 'abbreviation': 'ENE'},
                    {'name': 'Health Education', 'abbreviation': 'HED'},
                    {'name': 'Accounting Education', 'abbreviation': 'ACE'},
                    {'name': 'Agriculture Education', 'abbreviation': 'AGE'},
                    {'name': 'Building Construction Education', 'abbreviation': 'BCE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Electrical Electronics Education', 'abbreviation': 'EEE'},
                    {'name': 'Home Economics Education', 'abbreviation': 'HEE'},
                    {'name': 'Mechanical Engineering Education', 'abbreviation': 'MEE'},
                    {'name': 'Secretarial Education', 'abbreviation': 'SEE'},
                    {'name': 'Industrial Technical Education', 'abbreviation': 'ITE'},
                    {'name': 'Woodwork and Building Education', 'abbreviation': 'WBE'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural Engineering', 'abbreviation': 'AGE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Structural Engineering', 'abbreviation': 'STR'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Petroleum Engineering', 'abbreviation': 'PET'},
                    {'name': 'Industrial Engineering', 'abbreviation': 'IND'},
                    {'name': 'Metallurgical and Materials Engineering', 'abbreviation': 'MME'},
                    {'name': 'Mechatronic Engineering', 'abbreviation': 'MCE'},
                    {'name': 'Marine Engineering', 'abbreviation': 'MRE'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Geomatics', 'abbreviation': 'GEO'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Life Sciences',
                'abbreviation': 'LSC',
                'departments': [
                    {'name': 'Animal and Environmental Biology', 'abbreviation': 'AEB'},
                    {'name': 'Applied Geophysics', 'abbreviation': 'APG'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Environmental Management and Toxicology', 'abbreviation': 'EMT'},
                    {'name': 'Environmental Science', 'abbreviation': 'ESC'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Optometry', 'abbreviation': 'OPT'},
                    {'name': 'Plant Biology and Biotechnology', 'abbreviation': 'PBB'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Media and Communication Studies',
                'abbreviation': 'MCS',
                'departments': [
                    {'name': 'Public Relations', 'abbreviation': 'PRE'},
                    {'name': 'Film and Media Studies', 'abbreviation': 'FMS'},
                    {'name': 'Broadcasting', 'abbreviation': 'BRD'},
                    {'name': 'Advertising', 'abbreviation': 'ADV'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Taxation', 'abbreviation': 'TAX'},
                    {'name': 'Actuarial Science', 'abbreviation': 'ACT'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Finance', 'abbreviation': 'FIN'},
                    {'name': 'Human Resource Management', 'abbreviation': 'HRM'},
                    {'name': 'Industrial Relations and Personnel Management', 'abbreviation': 'IRP'},
                    {'name': 'Insurance', 'abbreviation': 'INS'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Office and Information Management', 'abbreviation': 'OIM'},
                    {'name': 'Tourism and Hospitality Management', 'abbreviation': 'THM'},
                ],
            },
            {
                'name': 'School of Medical Sciences',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                ],
            },
            {
                'name': 'Faculty of Pharmacy',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'Faculty of Physical Sciences',
                'abbreviation': 'PSC',
                'departments': [
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Pure and Applied Mathematics', 'abbreviation': 'PAM'},
                    {'name': 'Industrial Mathematics', 'abbreviation': 'IMT'},
                    {'name': 'Mathematics and Economics', 'abbreviation': 'MEC'},
                    {'name': 'Mathematics and Geography', 'abbreviation': 'MGE'},
                    {'name': 'Mathematics and Physics', 'abbreviation': 'MPH'},
                    {'name': 'Mathematics and Chemistry', 'abbreviation': 'MCH'},
                    {'name': 'Statistics with Computer', 'abbreviation': 'STC'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Political Science and Public Administration', 'abbreviation': 'PPA'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Sociology and Anthropology', 'abbreviation': 'SOA'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Geography and Regional Planning', 'abbreviation': 'GRP'},
                ],
            },
        ],
    },
    {
        'name': 'Ambrose Alli University, Ekpoma',
        'abbreviation': 'AAU',
        'state': 'EDO',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Languages, Literature and Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                ],
            },
            {
                'name': 'Faculty of Clinical Sciences',
                'abbreviation': 'CLM',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Community Medicine', 'abbreviation': 'CMH'},
                    {'name': 'Surgery', 'abbreviation': 'SUR'},
                    {'name': 'Paediatrics', 'abbreviation': 'PAE'},
                    {'name': 'Obstetrics and Gynaecology', 'abbreviation': 'OBG'},
                ],
            },
            {
                'name': 'Faculty of Communication Studies',
                'abbreviation': 'CMS',
                'departments': [
                    {'name': 'Communication and Media Studies', 'abbreviation': 'MAC'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Adult and Non-Formal Education', 'abbreviation': 'ANF'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Education Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education Integrated Science', 'abbreviation': 'EDIS'},
                    {'name': 'Education Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education Physics', 'abbreviation': 'EDP'},
                    {'name': 'Education Social Studies', 'abbreviation': 'EDSS'},
                    {'name': 'Education Geography', 'abbreviation': 'EDG'},
                    {'name': 'Education Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education Political Science', 'abbreviation': 'EDPS'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Engineering and Technology',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Studies',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Life Sciences',
                'abbreviation': 'LSC',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                    {'name': 'Plant Science and Biotechnology', 'abbreviation': 'PSB'},
                    {'name': 'Animal and Environmental Biology', 'abbreviation': 'AEB'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Medical Laboratory Sciences',
                'abbreviation': 'MLS',
                'departments': [
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                ],
            },
            {
                'name': 'Faculty of Physical Sciences',
                'abbreviation': 'PSC',
                'departments': [
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Geography and Regional Planning', 'abbreviation': 'GRP'},
                ],
            },
        ],
    },
    {
        'name': 'Igbinedion University, Okada',
        'abbreviation': 'IUO',
        'state': 'EDO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'College of Health Sciences',
                'abbreviation': 'CHS',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'College of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'College of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'College of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'International Relations and Diplomacy', 'abbreviation': 'IRD'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                ],
            },
            {
                'name': 'College of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biological Sciences', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Benson Idahosa University, Benin City',
        'abbreviation': 'BIU',
        'state': 'EDO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Arts and Education',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'English Studies', 'abbreviation': 'ENG'},
                    {'name': 'International Studies and Diplomacy', 'abbreviation': 'ISD'},
                    {'name': 'Agriculture Education', 'abbreviation': 'AGE'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Mathematics Education', 'abbreviation': 'MTE'},
                    {'name': 'Economics Education', 'abbreviation': 'EDE'},
                    {'name': 'Political Science Education', 'abbreviation': 'PSE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'English Education', 'abbreviation': 'EDEL'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                ],
            },
            {
                'name': 'Faculty of Agriculture and Agricultural Technology',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Animal Science and Livestock Production', 'abbreviation': 'ANS'},
                    {'name': 'Agronomy and Environmental Management', 'abbreviation': 'AEM'},
                    {'name': 'Agricultural Economics and Extension Services', 'abbreviation': 'AEC'},
                ],
            },
            {
                'name': 'College of Medicine',
                'abbreviation': 'MED',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Allied Health Sciences',
                'abbreviation': 'AHS',
                'departments': [
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Geophysics', 'abbreviation': 'GPH'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                ],
            },
            {
                'name': 'Faculty of Social and Management Sciences',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology and Anthropology', 'abbreviation': 'SOA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Peace Studies and Conflict Resolution', 'abbreviation': 'PCR'},
                ],
            },
        ],
    },
    {
        'name': 'Wellspring University, Benin City',
        'abbreviation': 'WELLSPRING',
        'state': 'EDO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'College of Health Sciences',
                'abbreviation': 'CHS',
                'departments': [
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                    {'name': 'Physiotherapy', 'abbreviation': 'PTP'},
                ],
            },
            {
                'name': 'College of Science and Computing',
                'abbreviation': 'CSC',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                ],
            },
            {
                'name': 'College of Social and Management Sciences',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
        ],
    },
    {
        'name': 'Samuel Adegboyega University, Ogwa',
        'abbreviation': 'SAU',
        'state': 'EDO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Humanities and Social Sciences',
                'abbreviation': 'HSS',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                ],
            },
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Education', 'abbreviation': 'EDN'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Auchi',
        'abbreviation': 'AUCHIPOLY',
        'state': 'EDO',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Agricultural Engineering Technology', 'abbreviation': 'AET'},
                    {'name': 'Civil Engineering Technology', 'abbreviation': 'CET'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                ],
            },
            {
                'name': 'School of Environmental Design',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'School of Industrial and Applied Sciences',
                'abbreviation': 'SIA',
                'departments': [
                    {'name': 'Arts and Design', 'abbreviation': 'ARD'},
                    {'name': 'Fashion Design and Clothing Technology', 'abbreviation': 'FDT'},
                    {'name': 'Food Technology', 'abbreviation': 'FST'},
                    {'name': 'Home and Rural Economics', 'abbreviation': 'HRE'},
                    {'name': 'Hospitality Management', 'abbreviation': 'HMT'},
                    {'name': 'Printing Technology', 'abbreviation': 'PRT'},
                ],
            },
            {
                'name': 'School of Information and Communication Technology',
                'abbreviation': 'SICT',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'School of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                ],
            },
        ],
    },
    {
        'name': 'Edo State Polytechnic, Usen',
        'abbreviation': 'EDOPOLY',
        'state': 'EDO',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'School of Environmental Design',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                ],
            },
        ],
    },
    {
        'name': 'Shaka Polytechnic, Benin City',
        'abbreviation': 'SHAKAPOLY',
        'state': 'EDO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'Lighthouse Polytechnic, Evbuobanosa',
        'abbreviation': 'LIGHTHOUSE',
        'state': 'EDO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'College of Education, Ekiadolor-Benin',
        'abbreviation': 'COEEKI',
        'state': 'EDO',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Social Studies', 'abbreviation': 'SST'},
                ],
            },
            {
                'name': 'School of Education',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Adult and Non-Formal Education', 'abbreviation': 'ANF'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Primary Education', 'abbreviation': 'PRI'},
                ],
            },
            {
                'name': 'School of Science and Vocational Education',
                'abbreviation': 'SSVE',
                'departments': [
                    {'name': 'Agricultural Science', 'abbreviation': 'AGR'},
                    {'name': 'Biology/Chemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology/Geography', 'abbreviation': 'BGE'},
                    {'name': 'Chemistry/Mathematics', 'abbreviation': 'CMA'},
                    {'name': 'Chemistry/Physics', 'abbreviation': 'CPH'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Home Economics', 'abbreviation': 'HEC'},
                    {'name': 'Integrated Science', 'abbreviation': 'ISC'},
                    {'name': 'Mathematics/Physics', 'abbreviation': 'MPH'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                ],
            },
        ],
    },
]