# academic_directory/management/commands/state_data/ekiti.py
"""Universities in Ekiti State. Add more universities to this list as needed."""

UNIVERSITIES = [
    {
        'name': 'Federal University, Oye-Ekiti',
        'abbreviation': 'FUOYE',
        'state': 'EKITI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEC'},
                    {'name': 'Animal Production and Health', 'abbreviation': 'APH'},
                    {'name': 'Crop Production and Horticulture', 'abbreviation': 'CPH'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Food Science and Technology', 'abbreviation': 'FST'},
                    {'name': 'Forestry and Wildlife Management', 'abbreviation': 'FWL'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                    {'name': 'Water Resources Management and Agrometeorology', 'abbreviation': 'WRM'},
                ],
            },
            {
                'name': 'Faculty of Arts and Humanities',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics and Languages', 'abbreviation': 'LIN'},
                    {'name': 'Religious and Cultural Studies', 'abbreviation': 'RCS'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Theatre and Media Arts', 'abbreviation': 'TMA'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Medical Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Medical Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Medical Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Physiotherapy', 'abbreviation': 'PTP'},
                ],
            },
            {
                'name': 'Faculty of Clinical Sciences',
                'abbreviation': 'CLM',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Adult Education', 'abbreviation': 'ADE'},
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and Computer Science', 'abbreviation': 'EDCS'},
                    {'name': 'Education and Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education and English Language', 'abbreviation': 'EDEL'},
                    {'name': 'Education and Integrated Science', 'abbreviation': 'EDIS'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Education and Social Studies', 'abbreviation': 'EDSS'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Technical Education', 'abbreviation': 'TED'},
                    {'name': 'Vocational Education', 'abbreviation': 'VCE'},
                ],
            },
            {
                'name': 'Faculty of Engineering and Technology',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural and Bio-resources Engineering', 'abbreviation': 'ABE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Materials and Metallurgical Engineering', 'abbreviation': 'MME'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Mechatronics Engineering', 'abbreviation': 'MCE'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Cooperative Economics and Management', 'abbreviation': 'CEM'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Insurance and Actuarial Science', 'abbreviation': 'INS'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                ],
            },
            {
                'name': 'Faculty of Pharmacy',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Animal and Environmental Biology', 'abbreviation': 'AEB'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Geophysics', 'abbreviation': 'GPH'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Plant Science and Biotechnology', 'abbreviation': 'PSB'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Criminology and Security Studies', 'abbreviation': 'CSS'},
                    {'name': 'Demography and Social Statistics', 'abbreviation': 'DSS'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Geography and Planning Science', 'abbreviation': 'GPS'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Peace and Conflict Studies', 'abbreviation': 'PCS'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Tourism and Hospitality Management', 'abbreviation': 'THM'},
                ],
            },
        ],
    },
    {
        'name': 'Ekiti State University, Ado-Ekiti',
        'abbreviation': 'EKSU',
        'state': 'EKITI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agricultural Science',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension Services', 'abbreviation': 'AEC'},
                    {'name': 'Animal Production and Health Sciences', 'abbreviation': 'APH'},
                    {'name': 'Crop, Horticulture and Landscape Design', 'abbreviation': 'CHL'},
                    {'name': 'Soil Resources and Environmental Management', 'abbreviation': 'SRE'},
                    {'name': 'Forestry Resources and Wildlife Management', 'abbreviation': 'FWL'},
                    {'name': 'Fisheries and Aquaculture Management', 'abbreviation': 'FIS'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'Religious Studies', 'abbreviation': 'RES'},
                    {'name': 'Islamic Religious Studies/Arabic', 'abbreviation': 'IRA'},
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Linguistics and Nigeria Languages', 'abbreviation': 'LIN'},
                    {'name': 'Theatre and Media Arts', 'abbreviation': 'TMA'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'Yoruba', 'abbreviation': 'YOR'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'English Education', 'abbreviation': 'EDEL'},
                    {'name': 'French Education', 'abbreviation': 'EDF'},
                    {'name': 'Yoruba Education', 'abbreviation': 'EDY'},
                    {'name': 'Education Christian Religious Studies', 'abbreviation': 'ECR'},
                    {'name': 'Education Arabic Studies', 'abbreviation': 'EDA'},
                    {'name': 'Education History', 'abbreviation': 'EDH'},
                    {'name': 'Biology Education', 'abbreviation': 'EDB'},
                    {'name': 'Mathematics Education', 'abbreviation': 'EDM'},
                    {'name': 'Chemistry Education', 'abbreviation': 'EDC'},
                    {'name': 'Basic/Integrated Science Education', 'abbreviation': 'EDIS'},
                    {'name': 'Computer Science Education', 'abbreviation': 'EDCS'},
                    {'name': 'Physics Education', 'abbreviation': 'EDP'},
                    {'name': 'Social Studies Education', 'abbreviation': 'EDSS'},
                    {'name': 'Economics Education', 'abbreviation': 'EDE'},
                    {'name': 'Political Science Education', 'abbreviation': 'EDPS'},
                    {'name': 'Geography Education', 'abbreviation': 'EDG'},
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Mechanical Technology Education', 'abbreviation': 'MTE'},
                    {'name': 'Building and Woodwork Technology Education', 'abbreviation': 'BWE'},
                    {'name': 'Electrical/Electronic Technology Education', 'abbreviation': 'ELE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Educational Technology', 'abbreviation': 'EDT'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Nursery and Primary/Early Childhood Education', 'abbreviation': 'ECE'},
                    {'name': 'Test, Measurement and Evaluation', 'abbreviation': 'TME'},
                    {'name': 'Human Kinetics/Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Health Education', 'abbreviation': 'HED'},
                    {'name': 'Adult Education', 'abbreviation': 'ADE'},
                    {'name': 'Educational Management', 'abbreviation': 'EDM'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Actuarial Science', 'abbreviation': 'ACT'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Insurance', 'abbreviation': 'INS'},
                    {'name': 'Cooperative Studies', 'abbreviation': 'COP'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Industrial Relations and Personnel Management', 'abbreviation': 'IRP'},
                ],
            },
            {
                'name': 'Faculty of Medicine',
                'abbreviation': 'MED',
                'departments': [
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Nursing', 'abbreviation': 'NSG'},
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PHL'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Geo-Physics', 'abbreviation': 'GPH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Plant Sciences and Biotechnology', 'abbreviation': 'PSB'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Geography and Planning Science', 'abbreviation': 'GPS'},
                    {'name': 'Tourism Studies', 'abbreviation': 'TRM'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Environmental Management', 'abbreviation': 'ENM'},
                ],
            },
        ],
    },
    {
        'name': 'Afe Babalola University, Ado-Ekiti',
        'abbreviation': 'ABUAD',
        'state': 'EKITI',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'College of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural Engineering', 'abbreviation': 'AGE'},
                    {'name': 'Aeronautical and Astronautical Engineering', 'abbreviation': 'AAE'},
                    {'name': 'Biomedical Engineering', 'abbreviation': 'BME'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronic Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Mechatronics Engineering', 'abbreviation': 'MCE'},
                    {'name': 'Petroleum Engineering', 'abbreviation': 'PET'},
                ],
            },
            {
                'name': 'College of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'College of Medicine and Health Sciences',
                'abbreviation': 'CMHS',
                'departments': [
                    {'name': 'Dentistry', 'abbreviation': 'DEN'},
                    {'name': 'Human Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Human Nutrition and Dietetics', 'abbreviation': 'HND'},
                    {'name': 'Human Physiology', 'abbreviation': 'PHL'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Medicine and Surgery', 'abbreviation': 'MBS'},
                    {'name': 'Nursing Science', 'abbreviation': 'NSG'},
                    {'name': 'Optometry', 'abbreviation': 'OPT'},
                    {'name': 'Pharmacology', 'abbreviation': 'PHC'},
                    {'name': 'Public Health', 'abbreviation': 'PUH'},
                ],
            },
            {
                'name': 'College of Pharmacy',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHM'},
                ],
            },
            {
                'name': 'College of Sciences',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Agriculture Science', 'abbreviation': 'AGR'},
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biotechnology', 'abbreviation': 'BTC'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geology', 'abbreviation': 'GLY'},
                    {'name': 'Human Biology', 'abbreviation': 'HUB'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Petroleum Chemistry', 'abbreviation': 'PCH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Physics with Electronics', 'abbreviation': 'PWE'},
                    {'name': 'Plant Science', 'abbreviation': 'PLS'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'College of Social and Management Sciences',
                'abbreviation': 'SMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Intelligence and Security Studies', 'abbreviation': 'ISS'},
                    {'name': 'International Relations and Diplomacy', 'abbreviation': 'IRD'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Media and Communication Studies', 'abbreviation': 'MAC'},
                    {'name': 'Peace and Conflict Studies', 'abbreviation': 'PCS'},
                    {'name': 'Performing Arts', 'abbreviation': 'PAF'},
                    {'name': 'Philosophy and Religious Studies', 'abbreviation': 'PHR'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Social Justice', 'abbreviation': 'SOJ'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Sport Science', 'abbreviation': 'SPS'},
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                    {'name': 'Tourism and Events Management', 'abbreviation': 'TEM'},
                ],
            },
        ],
    },
    {
        'name': 'Bamidele Olumilua University of Education, Science and Technology, Ikere-Ekiti',
        'abbreviation': 'BOUESTI',
        'state': 'EKITI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'College of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'French Education', 'abbreviation': 'EDF'},
                    {'name': 'Christian Religious Studies Education', 'abbreviation': 'ECR'},
                    {'name': 'English Education', 'abbreviation': 'EDEL'},
                    {'name': 'Educational Management', 'abbreviation': 'EDM'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Social Studies Education', 'abbreviation': 'SSE'},
                    {'name': 'Geography Education', 'abbreviation': 'EDG'},
                    {'name': 'Political Science Education', 'abbreviation': 'EDPS'},
                    {'name': 'Economics Education', 'abbreviation': 'EDE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Agricultural Science Education', 'abbreviation': 'ASE'},
                    {'name': 'Biology Education', 'abbreviation': 'EDB'},
                    {'name': 'Chemistry Education', 'abbreviation': 'EDC'},
                    {'name': 'Environmental Education', 'abbreviation': 'ENE'},
                    {'name': 'Home Economics Education', 'abbreviation': 'HEE'},
                    {'name': 'Integrated Science Education', 'abbreviation': 'ISE'},
                    {'name': 'Mathematics Education', 'abbreviation': 'EDM'},
                    {'name': 'Physics Education', 'abbreviation': 'EDP'},
                    {'name': 'Industrial Technology Education', 'abbreviation': 'ITE'},
                    {'name': 'Human Kinetics and Health Education', 'abbreviation': 'HKE'},
                    {'name': 'Human Kinetics and Sports Science', 'abbreviation': 'HKS'},
                    {'name': 'Educational Technology', 'abbreviation': 'EDT'},
                ],
            },
            {
                'name': 'College of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Plant Science and Biotechnology', 'abbreviation': 'PSB'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                ],
            },
            {
                'name': 'College of Technology',
                'abbreviation': 'TEC',
                'departments': [
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Tourism and Hospitality Management', 'abbreviation': 'THM'},
                    {'name': 'Food Science Technology', 'abbreviation': 'FST'},
                ],
            },
            {
                'name': 'College of Management Science',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BUA'},
                    {'name': 'Office and Information Management', 'abbreviation': 'OIM'},
                ],
            },
            {
                'name': 'College of Media and Performing Studies',
                'abbreviation': 'MPS',
                'departments': [
                    {'name': 'Theatre Arts', 'abbreviation': 'THA'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                ],
            },
            {
                'name': 'College of Peace and Security Studies',
                'abbreviation': 'PSS',
                'departments': [
                    {'name': 'Peace and Conflict Studies', 'abbreviation': 'PCS'},
                    {'name': 'Criminology and Security Studies', 'abbreviation': 'CSS'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Ado-Ekiti',
        'abbreviation': 'FEDPOLYADO',
        'state': 'EKITI',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Public Administration', 'abbreviation': 'PUA'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Agricultural Engineering Technology', 'abbreviation': 'AET'},
                    {'name': 'Civil Engineering Technology', 'abbreviation': 'CET'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronic Engineering Technology', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering Technology', 'abbreviation': 'MET'},
                ],
            },
            {
                'name': 'School of Environmental Design',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'School of Industrial and Applied Sciences',
                'abbreviation': 'SIA',
                'departments': [
                    {'name': 'Arts and Design', 'abbreviation': 'ARD'},
                    {'name': 'Fashion Design and Clothing Technology', 'abbreviation': 'FDT'},
                    {'name': 'Food Technology', 'abbreviation': 'FST'},
                    {'name': 'Home and Rural Economics', 'abbreviation': 'HRE'},
                    {'name': 'Hospitality Management', 'abbreviation': 'HMT'},
                    {'name': 'Printing Technology', 'abbreviation': 'PRT'},
                ],
            },
            {
                'name': 'School of Information and Communication Technology',
                'abbreviation': 'SICT',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'School of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                ],
            },
        ],
    },
    {
        'name': 'Crown Polytechnic, Ado-Ekiti',
        'abbreviation': 'CROWNPOLY',
        'state': 'EKITI',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'School of Business and Management',
                'abbreviation': 'SBM',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                ],
            },
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical/Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                ],
            },
            {
                'name': 'School of Environmental Design',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SST',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    {
        'name': 'College of Education, Ikere-Ekiti',
        'abbreviation': 'COEIKERE',
        'state': 'EKITI',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'French', 'abbreviation': 'FRE'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISC'},
                    {'name': 'Social Studies', 'abbreviation': 'SST'},
                    {'name': 'Yoruba', 'abbreviation': 'YOR'},
                ],
            },
            {
                'name': 'School of Education',
                'abbreviation': 'SED',
                'departments': [
                    {'name': 'Adult and Non-Formal Education', 'abbreviation': 'ANF'},
                    {'name': 'Early Childhood Education', 'abbreviation': 'ECE'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Primary Education', 'abbreviation': 'PRI'},
                ],
            },
            {
                'name': 'School of Science and Vocational Education',
                'abbreviation': 'SSVE',
                'departments': [
                    {'name': 'Agricultural Science Education', 'abbreviation': 'ASE'},
                    {'name': 'Biology Education', 'abbreviation': 'BIE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Chemistry Education', 'abbreviation': 'CHE'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Fine Arts Education', 'abbreviation': 'FAE'},
                    {'name': 'Geography Education', 'abbreviation': 'GEE'},
                    {'name': 'Home Economics', 'abbreviation': 'HEC'},
                    {'name': 'Integrated Science Education', 'abbreviation': 'ISE'},
                    {'name': 'Mathematics Education', 'abbreviation': 'MTE'},
                    {'name': 'Music Education', 'abbreviation': 'MUE'},
                    {'name': 'Physical and Health Education', 'abbreviation': 'PHE'},
                    {'name': 'Physics Education', 'abbreviation': 'PYE'},
                    {'name': 'Political Science Education', 'abbreviation': 'PSE'},
                ],
            },
        ],
    },
]