# academic_directory/management/commands/state_data/imo.py
"""
Universities in Imo State.
Add more universities to this list as needed.
"""

UNIVERSITIES = [
    {
        'name': 'Federal University of Technology, Owerri',
        'abbreviation': 'FUTO',
        'state': 'IMO',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Engineering and Engineering Technology',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Agricultural Engineering', 'abbreviation': 'AGE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Polymer and Textile Engineering', 'abbreviation': 'PTE'},
                ],
            },
            {
                'name': 'School of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Geosciences', 'abbreviation': 'GEO'},
                ],
            },
            {
                'name': 'School of Health Technology',
                'abbreviation': 'HTC',
                'departments': [
                    {'name': 'Optometry', 'abbreviation': 'OPT'},
                    {'name': 'Prosthetics and Orthotics', 'abbreviation': 'PRO'},
                    {'name': 'Public Health Technology', 'abbreviation': 'PHT'},
                ],
            },
            {
                'name': 'School of Agriculture and Agricultural Technology',
                'abbreviation': 'AAT',
                'departments': [
                    {'name': 'Agricultural Economics', 'abbreviation': 'AEC'},
                    {'name': 'Agricultural Extension', 'abbreviation': 'AEX'},
                    {'name': 'Animal Science and Technology', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science and Technology', 'abbreviation': 'CST'},
                    {'name': 'Soil Science and Technology', 'abbreviation': 'SST'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIA'},
                    {'name': 'Forestry and Wildlife Technology', 'abbreviation': 'FWT'},
                ],
            },
            {
                'name': 'School of Management Technology',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Project Management Technology', 'abbreviation': 'PMT'},
                    {'name': 'Transport Management Technology', 'abbreviation': 'TMT'},
                    {'name': 'Maritime Management Technology', 'abbreviation': 'MMT'},
                ],
            },
            {
                'name': 'School of Environmental Technology',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Environmental Technology', 'abbreviation': 'ENT'},
                    {'name': 'Surveying and Geoinformatics', 'abbreviation': 'SGI'},
                ],
            },
            {
                'name': 'School of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Physiology', 'abbreviation': 'PSL'},
                    {'name': 'Biomedical Technology', 'abbreviation': 'BMT'},
                ],
            },
        ],
    },
    {
        'name': 'Alvan Ikoku Federal University of Education',
        'abbreviation': 'AIFUE',
        'state': 'IMO',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Arts and Humanities',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'French', 'abbreviation': 'FRN'},
                    {'name': 'Igbo', 'abbreviation': 'IGB'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Music', 'abbreviation': 'MUS'},
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                    {'name': 'Creative Arts Education', 'abbreviation': 'CAE'},
                ],
            },
            {
                'name': 'Faculty of Science Education',
                'abbreviation': 'SCE',
                'departments': [
                    {'name': 'Biology Education', 'abbreviation': 'BIE'},
                    {'name': 'Chemistry Education', 'abbreviation': 'CHE'},
                    {'name': 'Physics Education', 'abbreviation': 'PHE'},
                    {'name': 'Mathematics Education', 'abbreviation': 'MTE'},
                    {'name': 'Integrated Science Education', 'abbreviation': 'ISE'},
                    {'name': 'Computer Education', 'abbreviation': 'CSE'},
                    {'name': 'Health Education', 'abbreviation': 'HED'},
                    {'name': 'Human Kinetics Education', 'abbreviation': 'HKE'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences Education',
                'abbreviation': 'SSE',
                'departments': [
                    {'name': 'Economics Education', 'abbreviation': 'ECE'},
                    {'name': 'Political Science Education', 'abbreviation': 'PSE'},
                    {'name': 'Social Studies Education', 'abbreviation': 'SOS'},
                    {'name': 'Geography Education', 'abbreviation': 'GEE'},
                ],
            },
            {
                'name': 'Faculty of Vocational and Technical Education',
                'abbreviation': 'VTE',
                'departments': [
                    {'name': 'Agricultural Education', 'abbreviation': 'AGE'},
                    {'name': 'Business Education', 'abbreviation': 'BUE'},
                    {'name': 'Home Economics Education', 'abbreviation': 'HEE'},
                    {'name': 'Technology Education', 'abbreviation': 'TED'},
                ],
            },
            {
                'name': 'Faculty of Educational Foundations',
                'abbreviation': 'EDF',
                'departments': [
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Adult and Non-Formal Education', 'abbreviation': 'ANF'},
                    {'name': 'Educational Administration and Planning', 'abbreviation': 'EAP'},
                ],
            },
        ],
    },
    {
        'name': 'National Open University of Nigeria',
        'abbreviation': 'NOUN',
        'state': 'IMO',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Agricultural Sciences',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEE'},
                    {'name': 'Animal Science and Fisheries', 'abbreviation': 'ANS'},
                    {'name': 'Crop and Soil Science', 'abbreviation': 'CSS'},
                ],
            },
            {
                'name': 'Faculty of Arts',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'Linguistics, Foreign and Nigerian Languages', 'abbreviation': 'LIN'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'Religious Studies', 'abbreviation': 'REL'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'COM',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Arts and Social Science Education', 'abbreviation': 'ASE'},
                    {'name': 'Science Education', 'abbreviation': 'SCE'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                ],
            },
            {
                'name': 'Faculty of Health Sciences',
                'abbreviation': 'HSC',
                'departments': [
                    {'name': 'Nursing Science', 'abbreviation': 'NRS'},
                    {'name': 'Public Health', 'abbreviation': 'PUB'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Public Administration', 'abbreviation': 'PAD'},
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BFN'},
                ],
            },
            {
                'name': 'Faculty of Sciences',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SSC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'International Relations', 'abbreviation': 'INR'},
                    {'name': 'Mass Communication', 'abbreviation': 'MSC'},
                    {'name': 'Political Science', 'abbreviation': 'POS'},
                ],
            },
        ],
    },
    {
        'name': 'Federal Polytechnic, Nekede',
        'abbreviation': 'NEKEDEPOLY',
        'state': 'IMO',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'School of Engineering Technology',
                'abbreviation': 'SET',
                'departments': [
                    {'name': 'Agricultural and Bio-Environmental Engineering', 'abbreviation': 'ABE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Mechatronics Engineering', 'abbreviation': 'MTE'},
                    {'name': 'Mineral and Petroleum Resources Engineering', 'abbreviation': 'MPE'},
                    {'name': 'Material and Metallurgical Engineering', 'abbreviation': 'MME'},
                    {'name': 'Welding and Fabrication Engineering', 'abbreviation': 'WFE'},
                ],
            },
            {
                'name': 'School of Industrial and Applied Sciences',
                'abbreviation': 'SIAS',
                'departments': [
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Food Technology', 'abbreviation': 'FOT'},
                    {'name': 'Mathematics and Statistics', 'abbreviation': 'MST'},
                    {'name': 'Fisheries Technology', 'abbreviation': 'FIT'},
                    {'name': 'Hospitality Management', 'abbreviation': 'HOM'},
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGT'},
                    {'name': 'Printing Technology', 'abbreviation': 'PRT'},
                    {'name': 'Pharmaceutical Technology', 'abbreviation': 'PHT'},
                ],
            },
            {
                'name': 'School of Business and Management Technology',
                'abbreviation': 'SBMT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BFN'},
                    {'name': 'Cooperative Economics and Management', 'abbreviation': 'CEM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                    {'name': 'Public Administration', 'abbreviation': 'PAD'},
                    {'name': 'Procurement and Supply Chain Management', 'abbreviation': 'PSM'},
                    {'name': 'Taxation', 'abbreviation': 'TAX'},
                ],
            },
            {
                'name': 'School of General Studies',
                'abbreviation': 'SGS',
                'departments': [
                    {'name': 'Mass Communication', 'abbreviation': 'MSC'},
                ],
            },
            {
                'name': 'School of Agriculture and Agricultural Technology',
                'abbreviation': 'SAAT',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGT'},
                    {'name': 'Animal Health and Production Technology', 'abbreviation': 'AHP'},
                    {'name': 'Fisheries Technology', 'abbreviation': 'FIT'},
                ],
            },
            {
                'name': 'School of Environmental Design and Technology',
                'abbreviation': 'SEDT',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                    {'name': 'Surveying and Geo-Informatics', 'abbreviation': 'SGI'},
                    {'name': 'Arts and Design Technology', 'abbreviation': 'ARD'},
                ],
            },
            {
                'name': 'School of Information and Communication Technology',
                'abbreviation': 'SICT',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Library and Information Science', 'abbreviation': 'LIS'},
                ],
            },
            {
                'name': 'School of Health and Related Technology',
                'abbreviation': 'SHRT',
                'departments': [
                    {'name': 'Dispensing Opticianry', 'abbreviation': 'OPT'},
                ],
            },
        ],
    },
    {
        'name': 'Imo State University',
        'abbreviation': 'IMSU',
        'state': 'IMO',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Political Science', 'abbreviation': 'POS'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'International Relations', 'abbreviation': 'INR'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'Religious Studies', 'abbreviation': 'REL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Hospitality and Tourism Management', 'abbreviation': 'HTM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BFN'},
                    {'name': 'Insurance and Actuarial Science', 'abbreviation': 'IAS'},
                    {'name': 'Management', 'abbreviation': 'MGT'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Physics Education', 'abbreviation': 'PHE'},
                    {'name': 'Biology Education', 'abbreviation': 'BIE'},
                    {'name': 'Chemistry Education', 'abbreviation': 'CHE'},
                    {'name': 'Geography Education', 'abbreviation': 'GEE'},
                    {'name': 'Computer Science Education', 'abbreviation': 'CSE'},
                    {'name': 'Mathematics Education', 'abbreviation': 'MTE'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biological Sciences', 'abbreviation': 'BIO'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Botany', 'abbreviation': 'BOT'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'Geology', 'abbreviation': 'GEL'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Zoology', 'abbreviation': 'ZOO'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Sharia Law', 'abbreviation': 'SHA'},
                    {'name': 'Public Law', 'abbreviation': 'PUL'},
                ],
            },
            {
                'name': 'Faculty of Pharmaceutical Sciences',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacognosy and Drug Development', 'abbreviation': 'PDD'},
                    {'name': 'Pharmaceutics and Pharmaceutical Technology', 'abbreviation': 'PPT'},
                    {'name': 'Clinical Pharmacy and Pharmacy Practice', 'abbreviation': 'CPP'},
                    {'name': 'Pharmaceutics and Medicinal Chemistry', 'abbreviation': 'PMC'},
                    {'name': 'Pharmacology and Therapeutics', 'abbreviation': 'PCT'},
                    {'name': 'Pharmaceutical Microbiology', 'abbreviation': 'PMB'},
                ],
            },
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEE'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QTS'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'College of Medical Sciences',
                'abbreviation': 'MED',
                'departments': [
                    {'name': 'Human Anatomy', 'abbreviation': 'ANA'},
                    {'name': 'Human Physiology', 'abbreviation': 'PSL'},
                    {'name': 'Medical Biochemistry', 'abbreviation': 'MBC'},
                    {'name': 'Chemical Pathology', 'abbreviation': 'CHP'},
                    {'name': 'Clinical Pharmacology and Therapeutics', 'abbreviation': 'CPT'},
                    {'name': 'Hematology and Blood Transfusion', 'abbreviation': 'HBT'},
                    {'name': 'Histopathology', 'abbreviation': 'HIS'},
                    {'name': 'Medical Microbiology and Immunology', 'abbreviation': 'MMI'},
                    {'name': 'Anaesthesia', 'abbreviation': 'ANE'},
                    {'name': 'E.N.T', 'abbreviation': 'ENT'},
                    {'name': 'Internal Medicine', 'abbreviation': 'INM'},
                    {'name': 'Community Medicine', 'abbreviation': 'COM'},
                    {'name': 'General Surgery', 'abbreviation': 'GSU'},
                    {'name': 'Paediatrics', 'abbreviation': 'PAE'},
                    {'name': 'Obstetrics and Gynaecology', 'abbreviation': 'OBG'},
                    {'name': 'Ophthalmology', 'abbreviation': 'OPH'},
                    {'name': 'Radiology', 'abbreviation': 'RAD'},
                ],
            },
        ],
    },
    {
        'name': 'Kingsley Ozumba Mbadiwe University',
        'abbreviation': 'KOMU',
        'state': 'IMO',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Arts and Social Sciences',
                'abbreviation': 'ASS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Political Science', 'abbreviation': 'POS'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'International Relations', 'abbreviation': 'INR'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                ],
            },
            {
                'name': 'Faculty of Science',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Computer Science', 'abbreviation': 'EDP'},
                    {'name': 'Education and Economics', 'abbreviation': 'EDE'},
                    {'name': 'Education and Social Studies', 'abbreviation': 'EDS'},
                    {'name': 'Education and English', 'abbreviation': 'EDL'},
                    {'name': 'Guidance and Counselling', 'abbreviation': 'GAC'},
                    {'name': 'Educational Foundations', 'abbreviation': 'EDF'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Pharmaceutical Sciences',
                'abbreviation': 'PHA',
                'departments': [
                    {'name': 'Pharmacy', 'abbreviation': 'PHR'},
                ],
            },
        ],
    },
    {
        'name': 'University of Agriculture and Environmental Sciences',
        'abbreviation': 'UAES',
        'state': 'IMO',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Extension', 'abbreviation': 'AEX'},
                    {'name': 'Agricultural Economics', 'abbreviation': 'AEC'},
                    {'name': 'Animal Production', 'abbreviation': 'ANP'},
                    {'name': 'Crop Production', 'abbreviation': 'CRP'},
                    {'name': 'Soil Science', 'abbreviation': 'SSL'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIA'},
                    {'name': 'Food Science and Technology', 'abbreviation': 'FST'},
                ],
            },
            {
                'name': 'Faculty of Science and Computing',
                'abbreviation': 'SAC',
                'departments': [
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Biotechnology', 'abbreviation': 'BTH'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Estate Management and Valuation', 'abbreviation': 'EMV'},
                    {'name': 'Environmental Management and Toxicology', 'abbreviation': 'EMT'},
                    {'name': 'Horticulture and Landscape Architecture', 'abbreviation': 'HLA'},
                ],
            },
            {
                'name': 'Faculty of Arts, Social and Management Sciences',
                'abbreviation': 'ASM',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Taxation', 'abbreviation': 'TAX'},
                    {'name': 'Peace Studies and Conflict Resolution', 'abbreviation': 'PCR'},
                    {'name': 'Criminology and Security Studies', 'abbreviation': 'CSS'},
                    {'name': 'Psychology', 'abbreviation': 'PSY'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Cooperative and Rural Development', 'abbreviation': 'CRD'},
                ],
            },
            {
                'name': 'Faculty of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Computer Engineering', 'abbreviation': 'CPE'},
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                ],
            },
        ],
    },
    {
        'name': 'Imo State Polytechnic',
        'abbreviation': 'IMOPOLY',
        'state': 'IMO',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Sciences',
                'abbreviation': 'SSC',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                    {'name': 'Mathematics and Statistics', 'abbreviation': 'MST'},
                    {'name': 'Food Science Technology', 'abbreviation': 'FST'},
                    {'name': 'Nutrition and Dietetics', 'abbreviation': 'NUD'},
                ],
            },
            {
                'name': 'School of Business',
                'abbreviation': 'SBS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BFN'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Cooperative Economics and Management', 'abbreviation': 'CEM'},
                    {'name': 'Public Administration', 'abbreviation': 'PAD'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                    {'name': 'Mass Communication', 'abbreviation': 'MSC'},
                    {'name': 'Hospitality Management', 'abbreviation': 'HOM'},
                ],
            },
            {
                'name': 'School of Agriculture',
                'abbreviation': 'SAG',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGT'},
                    {'name': 'Agricultural Extension and Management', 'abbreviation': 'AEM'},
                    {'name': 'Animal Production Technology', 'abbreviation': 'APT'},
                    {'name': 'Animal Health Technology', 'abbreviation': 'AHT'},
                    {'name': 'Crop Production Technology', 'abbreviation': 'CPT'},
                    {'name': 'Soil Science Technology', 'abbreviation': 'SST'},
                    {'name': 'Fisheries Technology', 'abbreviation': 'FIT'},
                    {'name': 'Forestry Technology', 'abbreviation': 'FOR'},
                    {'name': 'Horticulture Technology', 'abbreviation': 'HRT'},
                ],
            },
            {
                'name': 'School of Engineering',
                'abbreviation': 'SEN',
                'departments': [
                    {'name': 'Electrical and Electronics Engineering', 'abbreviation': 'EEE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Agricultural and Bio-Environmental Engineering', 'abbreviation': 'ABE'},
                ],
            },
            {
                'name': 'School of Environmental Design and Management Technology',
                'abbreviation': 'SEDT',
                'departments': [
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Estate Management', 'abbreviation': 'ESM'},
                    {'name': 'Environmental Management', 'abbreviation': 'ENM'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
        ],
    },
    {
        'name': 'Hezekiah University',
        'abbreviation': 'UNIHEZ',
        'state': 'IMO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'NAS',
                'departments': [
                    {'name': 'Plant Science and Biotechnology', 'abbreviation': 'PSB'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Mathematics and Statistics', 'abbreviation': 'MST'},
                    {'name': 'Physics with Electronics', 'abbreviation': 'PWE'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                ],
            },
            {
                'name': 'Faculty of Humanities',
                'abbreviation': 'HUM',
                'departments': [
                    {'name': 'English Language and Literary Studies', 'abbreviation': 'ELS'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                    {'name': 'Christian Religious Studies', 'abbreviation': 'CRS'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Political Science', 'abbreviation': 'POS'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Public Administration', 'abbreviation': 'PAD'},
                    {'name': 'Marketing', 'abbreviation': 'MKT'},
                    {'name': 'Mass Communication', 'abbreviation': 'MSC'},
                ],
            },
        ],
    },
    {
        'name': 'Maranathan University',
        'abbreviation': 'MARANATHAN',
        'state': 'IMO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'Faculty of Science and Technology',
                'abbreviation': 'SCT',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                    {'name': 'Information Technology', 'abbreviation': 'IFT'},
                ],
            },
            {
                'name': 'Faculty of Management and Social Sciences',
                'abbreviation': 'MSS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BFN'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Mass Communication', 'abbreviation': 'MSC'},
                    {'name': 'Political Science', 'abbreviation': 'POS'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
        ],
    },
    {
        'name': 'Claretian University of Nigeria',
        'abbreviation': 'CUN',
        'state': 'IMO',
        'type': 'PRIVATE',
        'faculties': [
            {
                'name': 'School of Agriculture',
                'abbreviation': 'SAG',
                'departments': [
                    {'name': 'Agricultural Science', 'abbreviation': 'AGS'},
                    {'name': 'Agricultural Economics', 'abbreviation': 'AEC'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CRP'},
                ],
            },
            {
                'name': 'School of Science and Computing',
                'abbreviation': 'SSC',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Cyber Security', 'abbreviation': 'CYB'},
                    {'name': 'Software Engineering', 'abbreviation': 'SWE'},
                    {'name': 'Biological Sciences', 'abbreviation': 'BIO'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                ],
            },
            {
                'name': 'School of Arts, Management and Social Sciences',
                'abbreviation': 'AMS',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'Political Science', 'abbreviation': 'POS'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                    {'name': 'Mass Communication', 'abbreviation': 'MSC'},
                    {'name': 'Philosophy', 'abbreviation': 'PHL'},
                    {'name': 'History and International Studies', 'abbreviation': 'HIS'},
                ],
            },
            {
                'name': 'School of Allied Health Sciences',
                'abbreviation': 'AHS',
                'departments': [
                    {'name': 'Nursing Science', 'abbreviation': 'NRS'},
                    {'name': 'Medical Laboratory Science', 'abbreviation': 'MLS'},
                    {'name': 'Public Health', 'abbreviation': 'PUB'},
                ],
            },
        ],
    },
]