# academic_directory/management/commands/state_data/katsina.py
"""Universities and Polytechnics in Katsina State."""

UNIVERSITIES = [
    # FEDERAL UNIVERSITY, DUTSIN-MA
    {
        'name': 'Federal University, Dutsin-Ma',
        'abbreviation': 'FUDMA',
        'state': 'KATSINA',
        'type': 'FEDERAL',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agricultural Economics and Extension', 'abbreviation': 'AEE'},
                    {'name': 'Animal Science', 'abbreviation': 'ANS'},
                    {'name': 'Crop Science', 'abbreviation': 'CPS'},
                    {'name': 'Fisheries and Aquaculture', 'abbreviation': 'FIS'},
                    {'name': 'Forestry and Wildlife Management', 'abbreviation': 'FWM'},
                    {'name': 'Soil Science', 'abbreviation': 'SLS'},
                ],
            },
            {
                'name': 'Faculty of Arts and Social Sciences',
                'abbreviation': 'ART',
                'departments': [
                    {'name': 'Arabic Studies', 'abbreviation': 'ARB'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'English Language', 'abbreviation': 'ENG'},
                    {'name': 'French', 'abbreviation': 'FRN'},
                    {'name': 'History and Diplomatic Studies', 'abbreviation': 'HIS'},
                    {'name': 'International Relations and Diplomacy', 'abbreviation': 'IRD'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISL'},
                    {'name': 'Linguistics', 'abbreviation': 'LIN'},
                    {'name': 'Mass Communication', 'abbreviation': 'MAC'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'Faculty of Computing',
                'abbreviation': 'COM',
                'departments': [
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Information Technology', 'abbreviation': 'IT'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Business Education', 'abbreviation': 'BED'},
                    {'name': 'Early Childhood Education', 'abbreviation': 'ECE'},
                    {'name': 'Education and Biology', 'abbreviation': 'EDB'},
                    {'name': 'Education and Chemistry', 'abbreviation': 'EDC'},
                    {'name': 'Education and English Language', 'abbreviation': 'EDE'},
                    {'name': 'Education and Mathematics', 'abbreviation': 'EDM'},
                    {'name': 'Education and Physics', 'abbreviation': 'EDP'},
                    {'name': 'Educational Administration', 'abbreviation': 'EDA'},
                    {'name': 'Human Kinetics and Health Education', 'abbreviation': 'HKH'},
                    {'name': 'Primary Education', 'abbreviation': 'PED'},
                    {'name': 'Special Education', 'abbreviation': 'SPE'},
                    {'name': 'Teacher Education Science', 'abbreviation': 'TES'},
                ],
            },
            {
                'name': 'Faculty of Engineering and Technology',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural and Bio-Resources Engineering', 'abbreviation': 'ABE'},
                    {'name': 'Chemical Engineering', 'abbreviation': 'CHE'},
                    {'name': 'Civil Engineering', 'abbreviation': 'CVE'},
                    {'name': 'Electrical/Electronic Engineering', 'abbreviation': 'ELE'},
                    {'name': 'Mechanical Engineering', 'abbreviation': 'MEE'},
                    {'name': 'Mechatronics Engineering', 'abbreviation': 'MTR'},
                ],
            },
            {
                'name': 'Faculty of Environmental Sciences',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architecture', 'abbreviation': 'ARC'},
                    {'name': 'Building', 'abbreviation': 'BLD'},
                    {'name': 'Environmental Management', 'abbreviation': 'ENV'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QSV'},
                    {'name': 'Urban and Regional Planning', 'abbreviation': 'URP'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Law', 'abbreviation': 'LAW'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accounting', 'abbreviation': 'ACC'},
                    {'name': 'Banking and Finance', 'abbreviation': 'BNF'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Entrepreneurship', 'abbreviation': 'ENT'},
                    {'name': 'Taxation', 'abbreviation': 'TAX'},
                ],
            },
            {
                'name': 'Faculty of Sciences',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Applied Geophysics', 'abbreviation': 'APH'},
                    {'name': 'Biological Sciences', 'abbreviation': 'BIO'},
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Geology', 'abbreviation': 'GEO'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
        ],
    },
    
    # UMARU MUSA YAR'ADUA UNIVERSITY, KATSINA
    {
        'name': 'Umaru Musa Yar\'adua University',
        'abbreviation': 'UMYU',
        'state': 'KATSINA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'Faculty of Agriculture',
                'abbreviation': 'AGR',
                'departments': [
                    {'name': 'Agriculture', 'abbreviation': 'AGR'},
                    {'name': 'Aquaculture', 'abbreviation': 'AQU'},
                    {'name': 'Fisheries', 'abbreviation': 'FIS'},
                    {'name': 'Forestry', 'abbreviation': 'FOR'},
                    {'name': 'Wildlife', 'abbreviation': 'WLD'},
                ],
            },
            {
                'name': 'Faculty of Basic Medical Sciences',
                'abbreviation': 'BMS',
                'departments': [
                    {'name': 'Medicine', 'abbreviation': 'MED'},
                    {'name': 'Surgery', 'abbreviation': 'SUR'},
                ],
            },
            {
                'name': 'Faculty of Earth and Environmental Sciences',
                'abbreviation': 'EES',
                'departments': [
                    {'name': 'Environmental Studies', 'abbreviation': 'ENV'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'Meteorology', 'abbreviation': 'MET'},
                ],
            },
            {
                'name': 'Faculty of Education',
                'abbreviation': 'EDU',
                'departments': [
                    {'name': 'Education', 'abbreviation': 'EDU'},
                    {'name': 'Information Sciences', 'abbreviation': 'INF'},
                    {'name': 'Library Science', 'abbreviation': 'LIS'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Special Education', 'abbreviation': 'SPE'},
                    {'name': 'Vocational Education', 'abbreviation': 'VOC'},
                ],
            },
            {
                'name': 'Faculty of Humanities',
                'abbreviation': 'HUM',
                'departments': [
                    {'name': 'African Languages', 'abbreviation': 'AFL'},
                    {'name': 'Arabic', 'abbreviation': 'ARB'},
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'French', 'abbreviation': 'FRN'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISL'},
                ],
            },
            {
                'name': 'Faculty of Law',
                'abbreviation': 'LAW',
                'departments': [
                    {'name': 'Islamic Law', 'abbreviation': 'ISL'},
                    {'name': 'Private Law', 'abbreviation': 'PRL'},
                    {'name': 'Public Law', 'abbreviation': 'PUL'},
                ],
            },
            {
                'name': 'Faculty of Management Sciences',
                'abbreviation': 'MGT',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration', 'abbreviation': 'BAD'},
                    {'name': 'Development Studies', 'abbreviation': 'DEV'},
                    {'name': 'Government', 'abbreviation': 'GOV'},
                    {'name': 'Public Administration', 'abbreviation': 'PAD'},
                ],
            },
            {
                'name': 'Faculty of Natural and Applied Sciences',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Biochemistry', 'abbreviation': 'BCH'},
                    {'name': 'Biology', 'abbreviation': 'BIO'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Industrial Chemistry', 'abbreviation': 'ICH'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Microbiology', 'abbreviation': 'MCB'},
                    {'name': 'Physics', 'abbreviation': 'PHY'},
                    {'name': 'Statistics', 'abbreviation': 'STA'},
                ],
            },
            {
                'name': 'Faculty of Social Sciences',
                'abbreviation': 'SOC',
                'departments': [
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'International Relations and Diplomacy', 'abbreviation': 'IRD'},
                    {'name': 'Political Science', 'abbreviation': 'POL'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'School of Continuing Education',
                'abbreviation': 'SCE',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Arabic', 'abbreviation': 'ARB'},
                    {'name': 'Economics', 'abbreviation': 'ECO'},
                    {'name': 'English', 'abbreviation': 'ENG'},
                    {'name': 'Foreign Languages Education', 'abbreviation': 'FLE'},
                    {'name': 'French', 'abbreviation': 'FRN'},
                    {'name': 'Hausa', 'abbreviation': 'HAU'},
                    {'name': 'History', 'abbreviation': 'HIS'},
                    {'name': 'Humanities and Social Science Education', 'abbreviation': 'HSE'},
                    {'name': 'Information Sciences', 'abbreviation': 'INF'},
                    {'name': 'Library Science', 'abbreviation': 'LIS'},
                    {'name': 'Mathematics Education', 'abbreviation': 'MTH'},
                    {'name': 'Native Language Education', 'abbreviation': 'NLE'},
                    {'name': 'Political Sciences', 'abbreviation': 'POL'},
                    {'name': 'Public Administration', 'abbreviation': 'PAD'},
                    {'name': 'Science Education', 'abbreviation': 'SED'},
                    {'name': 'Sociology', 'abbreviation': 'SOC'},
                ],
            },
            {
                'name': 'School of Postgraduate Studies',
                'abbreviation': 'PGS',
                'departments': [
                    {'name': 'Arabic', 'abbreviation': 'ARB'},
                    {'name': 'Arts and Humanities', 'abbreviation': 'ART'},
                    {'name': 'Chemistry', 'abbreviation': 'CHM'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Curriculum Studies', 'abbreviation': 'CUR'},
                    {'name': 'Education', 'abbreviation': 'EDU'},
                    {'name': 'Educational Psychology', 'abbreviation': 'EDP'},
                    {'name': 'Geography', 'abbreviation': 'GEO'},
                    {'name': 'Islamic Studies', 'abbreviation': 'ISL'},
                    {'name': 'Mathematics', 'abbreviation': 'MTH'},
                    {'name': 'Natural Resources', 'abbreviation': 'NRS'},
                    {'name': 'Natural Sciences', 'abbreviation': 'NSC'},
                ],
            },
        ],
    },
    
    # HASSAN USMAN KATSINA POLYTECHNIC
    {
        'name': 'Hassan Usman Katsina Polytechnic',
        'abbreviation': 'HUKPOLY',
        'state': 'KATSINA',
        'type': 'STATE',
        'faculties': [
            {
                'name': 'School of Business Studies',
                'abbreviation': 'BUS',
                'departments': [
                    {'name': 'Accountancy', 'abbreviation': 'ACC'},
                    {'name': 'Business Administration and Management', 'abbreviation': 'BAM'},
                    {'name': 'Office Technology and Management', 'abbreviation': 'OTM'},
                    {'name': 'Public Administration', 'abbreviation': 'PAD'},
                ],
            },
            {
                'name': 'School of Engineering',
                'abbreviation': 'ENG',
                'departments': [
                    {'name': 'Agricultural Engineering Technology', 'abbreviation': 'AGE'},
                    {'name': 'Welding and Fabrication Technology', 'abbreviation': 'WLD'},
                ],
            },
            {
                'name': 'School of Environmental Studies',
                'abbreviation': 'ENV',
                'departments': [
                    {'name': 'Architectural Technology', 'abbreviation': 'ARC'},
                    {'name': 'Building Technology', 'abbreviation': 'BLD'},
                    {'name': 'Quantity Surveying', 'abbreviation': 'QSV'},
                ],
            },
            {
                'name': 'School of Science and Technology',
                'abbreviation': 'SCI',
                'departments': [
                    {'name': 'Agricultural Technology', 'abbreviation': 'AGT'},
                    {'name': 'Animal Health and Production Technology', 'abbreviation': 'AHP'},
                    {'name': 'Computer Science', 'abbreviation': 'CSC'},
                    {'name': 'Forestry Technology', 'abbreviation': 'FOR'},
                    {'name': 'Home and Rural Economics', 'abbreviation': 'HRE'},
                    {'name': 'Hospitality Management', 'abbreviation': 'HSM'},
                    {'name': 'Nutrition and Dietetics', 'abbreviation': 'NDT'},
                    {'name': 'Science Laboratory Technology', 'abbreviation': 'SLT'},
                ],
            },
        ],
    },
]