# Generated by Django 5.1.3 on 2026-02-23 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrderLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, help_text='Auto-generated from organization name', max_length=300, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_branding_enabled', models.BooleanField(default=False)),
                ('payment_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Order Link',
                'verbose_name_plural': 'Bulk Order Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='bulk_orders.bulkorderlink')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.PositiveIntegerField(editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('XXXL', '3X Large'), ('XXXXL', '4X Large')], max_length=10)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bulk_orders.bulkorderlink')),
                ('coupon_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulk_orders.couponcode')),
            ],
            options={
                'verbose_name': 'Order Entry',
                'verbose_name_plural': 'Order Entries',
                'ordering': ['bulk_order', 'serial_number'],
            },
        ),
        migrations.AddIndex(
            model_name='bulkorderlink',
            index=models.Index(fields=['created_by', 'payment_deadline'], name='bulk_order_user_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkorderlink',
            index=models.Index(fields=['organization_name'], name='bulk_order_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkorderlink',
            index=models.Index(fields=['created_at'], name='bulk_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkorderlink',
            index=models.Index(fields=['slug'], name='bulk_order_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['bulk_order', 'is_used'], name='coupon_bulk_order_used_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['code'], name='coupon_code_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['bulk_order', 'serial_number'], name='order_bulk_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['email'], name='order_email_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['paid'], name='order_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['size'], name='order_size_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['created_at'], name='order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['updated_at'], name='order_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='orderentry',
            index=models.Index(fields=['reference'], name='order_reference_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderentry',
            unique_together={('bulk_order', 'serial_number')},
        ),
    ]
