# Generated by Django 5.1.3 on 2026-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='reference',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
