# Generated by Django 5.1.3 on 2026-02-23 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who verified this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_representatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='representativehistory',
            name='department',
            field=models.ForeignKey(help_text='Department at time of snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_directory.department'),
        ),
        migrations.AddField(
            model_name='representativehistory',
            name='faculty',
            field=models.ForeignKey(help_text='Faculty at time of snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_directory.faculty'),
        ),
        migrations.AddField(
            model_name='representativehistory',
            name='representative',
            field=models.ForeignKey(help_text='Representative this history belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='academic_directory.representative'),
        ),
        migrations.AddField(
            model_name='submissionnotification',
            name='read_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who read this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionnotification',
            name='representative',
            field=models.OneToOneField(help_text='Representative this notification is for', on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='academic_directory.representative'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['abbreviation'], name='academic_di_abbrevi_29b27c_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['state'], name='academic_di_state_89b6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['type'], name='academic_di_type_a359e0_idx'),
        ),
        migrations.AddField(
            model_name='representativehistory',
            name='university',
            field=models.ForeignKey(help_text='University at time of snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_directory.university'),
        ),
        migrations.AddField(
            model_name='representative',
            name='university',
            field=models.ForeignKey(help_text='University (denormalized for faster queries)', on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='academic_directory.university'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(help_text='University this faculty belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='academic_directory.university'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['faculty', 'name'], name='academic_di_faculty_4e9018_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['abbreviation'], name='academic_di_abbrevi_268d7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('faculty', 'name')},
        ),
        migrations.AddIndex(
            model_name='submissionnotification',
            index=models.Index(fields=['is_read', '-created_at'], name='academic_di_is_read_fe9391_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionnotification',
            index=models.Index(fields=['is_emailed'], name='academic_di_is_emai_403357_idx'),
        ),
        migrations.AddIndex(
            model_name='representativehistory',
            index=models.Index(fields=['representative', '-snapshot_date'], name='academic_di_represe_9b64ec_idx'),
        ),
        migrations.AddIndex(
            model_name='representativehistory',
            index=models.Index(fields=['phone_number'], name='academic_di_phone_n_b88114_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['phone_number'], name='academic_di_phone_n_d8b6af_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['department', 'role'], name='academic_di_departm_e49278_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['faculty', 'role'], name='academic_di_faculty_be8b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['university', 'role'], name='academic_di_univers_ad1619_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['verification_status'], name='academic_di_verific_356da0_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['is_active'], name='academic_di_is_acti_2efacf_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['entry_year'], name='academic_di_entry_y_f5ccdc_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['tenure_start_year'], name='academic_di_tenure__ce8b76_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['university', 'name'], name='academic_di_univers_9de54e_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['abbreviation'], name='academic_di_abbrevi_e45458_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('university', 'name')},
        ),
    ]
