# Generated by Django 5.1.3 on 2026-02-23 09:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Enter an 11-digit phone number', max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits', regex='^\\d{11}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('items_generated', models.BooleanField(default=False, help_text='Whether order items have been generated/printed')),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the order items were generated', null=True)),
                ('generated_by', models.ForeignKey(blank=True, help_text='Admin user who generated the order items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ChurchOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.baseorder')),
                ('pickup_on_camp', models.BooleanField(default=True)),
                ('delivery_state', models.CharField(blank=True, max_length=50)),
                ('delivery_lga', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Church Order',
                'verbose_name_plural': 'Church Orders',
            },
            bases=('order.baseorder',),
        ),
        migrations.CreateModel(
            name='NyscKitOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.baseorder')),
                ('call_up_number', models.CharField(help_text='NYSC call-up number (e.g., AB/22C/1234)', max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('local_government', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'NYSC Kit Order',
                'verbose_name_plural': 'NYSC Kit Orders',
            },
            bases=('order.baseorder',),
        ),
        migrations.CreateModel(
            name='NyscTourOrder',
            fields=[
                ('baseorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.baseorder')),
            ],
            options={
                'verbose_name': 'NYSC Tour Order',
                'verbose_name_plural': 'NYSC Tour Orders',
            },
            bases=('order.baseorder',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.baseorder')),
            ],
        ),
    ]
