# Generated by Django 5.1.3 on 2026-02-23 06:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the measurement set', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When these measurements were first recorded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When these measurements were last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - marks measurement as deleted without removing from database')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, help_text='Chest circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20.00')), django.core.validators.MaxValueValidator(Decimal('70.00'))])),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, help_text='Shoulder width in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('12.00')), django.core.validators.MaxValueValidator(Decimal('30.00'))])),
                ('neck', models.DecimalField(blank=True, decimal_places=2, help_text='Neck circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10.00')), django.core.validators.MaxValueValidator(Decimal('30.00'))])),
                ('sleeve_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length from shoulder to wrist in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20.00')), django.core.validators.MaxValueValidator(Decimal('40.00'))])),
                ('sleeve_round', models.DecimalField(blank=True, decimal_places=2, help_text='Bicep circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('8.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('top_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length from shoulder to desired shirt bottom in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20.00')), django.core.validators.MaxValueValidator(Decimal('40.00'))])),
                ('waist', models.DecimalField(blank=True, decimal_places=2, help_text='Waist circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20.00')), django.core.validators.MaxValueValidator(Decimal('60.00'))])),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, help_text='Thigh circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('12.00')), django.core.validators.MaxValueValidator(Decimal('40.00'))])),
                ('knee', models.DecimalField(blank=True, decimal_places=2, help_text='Knee circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('10.00')), django.core.validators.MaxValueValidator(Decimal('30.00'))])),
                ('ankle', models.DecimalField(blank=True, decimal_places=2, help_text='Ankle circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('7.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('hips', models.DecimalField(blank=True, decimal_places=2, help_text='Hip circumference in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('25.00')), django.core.validators.MaxValueValidator(Decimal('70.00'))])),
                ('trouser_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length from waist to ankle in inches', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('25.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))])),
                ('user', models.ForeignKey(help_text='User these measurements belong to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='measurement_user_created_idx')],
            },
        ),
    ]
