# Generated by Django 5.1.3 on 2026-02-23 06:59

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(choices=[('NYSC KIT', 'NYSC KIT'), ('NYSC TOUR', 'NYSC TOUR'), ('CHURCH PROGRAMME', 'CHURCH PROGRAMME')], max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('product_type', models.CharField(choices=[('nysc_kit', 'NYSC Kit'), ('nysc_tour', 'NYSC Tour'), ('church', 'CHURCH')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ca_name_693421_idx'), models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'), models.Index(fields=['product_type'], name='products_ca_product_9e88ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_1', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_2', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_3', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('available', models.BooleanField(default=True, help_text='Controls whether the product is visible on the site')),
                ('out_of_stock', models.BooleanField(default=False, help_text='Controls whether the product can be purchased')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Quality Shilo Shirt', 'QUALITY SHILO SHIRT'), ('Quality RCCG Shirt', 'QUALITY RCCG SHIRT'), ('Quality RCCG Shirt jacket', 'QUALITY RCCG JACKET'), ('Quality shilo jacket', 'QUALITY SHILO JACKET'), ('Quality RCCG polo', 'QUALITY RCCG POLO'), ('Quality shilo polo', 'QUALITY SHILO POLO')], max_length=100, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=200)),
                ('church', models.CharField(choices=[('', 'Select Church'), ('WINNERS', 'WINNERS Chapel'), ('RCCG', 'Redeemed Christian Church of God (RCCG)'), ('DEEPER_LIFE', 'Deeper Life Bible Church'), ('MOUNTAIN_OF_FIRE', 'Mountain of Fire and Miracles (MFM)'), ('CHRIST_EMBASSY', 'Christ Embassy'), ('LIVING_FAITH', 'Living Faith Church (Winners Chapel)'), ('DAYSTAR', 'Daystar Christian Centre'), ('COVENANT', 'Covenant Christian Centre')], max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='products.category')),
            ],
            options={
                'verbose_name': 'church',
                'verbose_name_plural': 'churchies',
                'ordering': ['id'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='products_ch_name_5c0722_idx'), models.Index(fields=['slug'], name='products_ch_slug_7ec679_idx'), models.Index(fields=['church'], name='products_ch_church_ab62ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='NyscKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_1', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_2', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_3', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('available', models.BooleanField(default=True, help_text='Controls whether the product is visible on the site')),
                ('out_of_stock', models.BooleanField(default=False, help_text='Controls whether the product can be purchased')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Quality Nysc Kakhi', 'Quality NYSC Kakhi'), ('Quality Nysc Vest', 'Quality NYSC Vest'), ('Quality Nysc Cap', 'Quality NYSC Cap')], max_length=100, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=200)),
                ('type', models.CharField(choices=[('kakhi', 'Kakhi'), ('vest', 'Vest'), ('cap', 'Cap')], help_text='Select the type of NYSC Kit product', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='products.category')),
            ],
            options={
                'verbose_name': 'nysckit',
                'verbose_name_plural': 'nysckits',
                'ordering': [models.Case(models.When(then=0, type='kakhi'), models.When(then=2, type='vest'), models.When(then=1, type='cap'), default=3), 'type'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='products_ny_name_d97dca_idx'), models.Index(fields=['slug'], name='products_ny_slug_5d85ca_idx'), models.Index(fields=['type'], name='products_ny_type_c88e72_idx')],
            },
        ),
        migrations.CreateModel(
            name='NyscTour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_1', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_2', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('image_3', models.ImageField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('available', models.BooleanField(default=True, help_text='Controls whether the product is visible on the site')),
                ('out_of_stock', models.BooleanField(default=False, help_text='Controls whether the product can be purchased')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('', 'Select State'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'Federal Capital Territory (FCT)'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=100, verbose_name='Product Name')),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='products.category')),
            ],
            options={
                'verbose_name': 'nysctour',
                'verbose_name_plural': 'nysctours',
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='products_ny_name_3f5c75_idx'), models.Index(fields=['slug'], name='products_ny_slug_dcf337_idx')],
            },
        ),
    ]
